# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z
# Application-level enforcement helpers. MongoDB has no foreign keys, cascades,
# defaults or sequences: these functions re-create the guarantees marked
# CHANGED or BROKEN by the equivalence checker.
# Requires migrate.py next to this file (or schemashift installed).

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from bson import ObjectId

try:
    from schemashift.codegen.runtime_migrate import convert_value, row_to_doc
except ImportError:  # generated deployment: migrate.py sits next to helpers.py
    from migrate import convert_value, row_to_doc  # type: ignore[import-not-found,no-redef]

PLAN = {'options': {'uuid_as': 'binary', 'preserve_integer_ids': False},
 'roots': ['departments', 'students'],
 'tables': {'departments': {'kind': 'root',
                            'collection': 'departments',
                            'host': None,
                            'path': [],
                            'dropped': [],
                            'host_columns': [],
                            'id_column': 'id',
                            'fields': {'id': '_id', 'name': 'name', 'budget': 'budget'},
                            'scalar_column': None,
                            'pk': ['id'],
                            'identity': ['id'],
                            'columns': {'id': {'base': 'INTEGER',
                                               'is_array': False,
                                               'nullable': False},
                                        'name': {'base': 'TEXT',
                                                 'is_array': False,
                                                 'nullable': False},
                                        'budget': {'base': 'DECIMAL',
                                                   'is_array': False,
                                                   'nullable': True}}},
            'professors': {'kind': 'array',
                           'collection': 'departments',
                           'host': 'departments',
                           'path': ['professors'],
                           'dropped': ['department_id'],
                           'host_columns': ['id'],
                           'id_column': None,
                           'fields': {'id': 'id', 'name': 'name', 'email': 'email'},
                           'scalar_column': None,
                           'pk': ['id'],
                           'identity': ['id'],
                           'columns': {'id': {'base': 'INTEGER',
                                              'is_array': False,
                                              'nullable': False},
                                       'name': {'base': 'TEXT',
                                                'is_array': False,
                                                'nullable': False},
                                       'email': {'base': 'TEXT',
                                                 'is_array': False,
                                                 'nullable': False},
                                       'department_id': {'base': 'INTEGER',
                                                         'is_array': False,
                                                         'nullable': False}}},
            'students': {'kind': 'root',
                         'collection': 'students',
                         'host': None,
                         'path': [],
                         'dropped': [],
                         'host_columns': [],
                         'id_column': 'id',
                         'fields': {'id': '_id',
                                    'name': 'name',
                                    'email': 'email',
                                    'enrolled_on': 'enrolled_on',
                                    'advisor_id': 'advisor_id',
                                    'gpa': 'gpa'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'name': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                     'email': {'base': 'TEXT',
                                               'is_array': False,
                                               'nullable': False},
                                     'enrolled_on': {'base': 'DATE',
                                                     'is_array': False,
                                                     'nullable': False},
                                     'advisor_id': {'base': 'INTEGER',
                                                    'is_array': False,
                                                    'nullable': True},
                                     'gpa': {'base': 'DECIMAL',
                                             'is_array': False,
                                             'nullable': True}}},
            'courses': {'kind': 'array',
                        'collection': 'departments',
                        'host': 'departments',
                        'path': ['courses'],
                        'dropped': ['department_id'],
                        'host_columns': ['id'],
                        'id_column': None,
                        'fields': {'id': 'id',
                                   'code': 'code',
                                   'title': 'title',
                                   'credits': 'credits'},
                        'scalar_column': None,
                        'pk': ['id'],
                        'identity': ['id'],
                        'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                    'code': {'base': 'VARCHAR',
                                             'is_array': False,
                                             'nullable': False},
                                    'title': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                    'credits': {'base': 'INTEGER',
                                                'is_array': False,
                                                'nullable': False},
                                    'department_id': {'base': 'INTEGER',
                                                      'is_array': False,
                                                      'nullable': False}}},
            'prerequisites': {'kind': 'array',
                              'collection': 'departments',
                              'host': 'courses',
                              'path': ['courses', 'prerequisites'],
                              'dropped': ['course_id'],
                              'host_columns': ['id'],
                              'id_column': None,
                              'fields': {'requires_id': 'requires_id'},
                              'scalar_column': None,
                              'pk': ['course_id', 'requires_id'],
                              'identity': [],
                              'columns': {'course_id': {'base': 'INTEGER',
                                                        'is_array': False,
                                                        'nullable': False},
                                          'requires_id': {'base': 'INTEGER',
                                                          'is_array': False,
                                                          'nullable': False}}},
            'sections': {'kind': 'array',
                         'collection': 'departments',
                         'host': 'courses',
                         'path': ['courses', 'sections'],
                         'dropped': ['course_id'],
                         'host_columns': ['id'],
                         'id_column': None,
                         'fields': {'id': 'id',
                                    'professor_id': 'professor_id',
                                    'term': 'term',
                                    'room': 'room'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'course_id': {'base': 'INTEGER',
                                                   'is_array': False,
                                                   'nullable': False},
                                     'professor_id': {'base': 'INTEGER',
                                                      'is_array': False,
                                                      'nullable': True},
                                     'term': {'base': 'VARCHAR',
                                              'is_array': False,
                                              'nullable': False},
                                     'room': {'base': 'TEXT',
                                              'is_array': False,
                                              'nullable': True}}},
            'enrollments': {'kind': 'array',
                            'collection': 'students',
                            'host': 'students',
                            'path': ['enrollments'],
                            'dropped': ['student_id'],
                            'host_columns': ['id'],
                            'id_column': None,
                            'fields': {'section_id': 'section_id', 'grade': 'grade'},
                            'scalar_column': None,
                            'pk': ['student_id', 'section_id'],
                            'identity': [],
                            'columns': {'student_id': {'base': 'INTEGER',
                                                       'is_array': False,
                                                       'nullable': False},
                                        'section_id': {'base': 'INTEGER',
                                                       'is_array': False,
                                                       'nullable': False},
                                        'grade': {'base': 'ENUM',
                                                  'is_array': False,
                                                  'nullable': True}}},
            'office_hours': {'kind': 'array',
                             'collection': 'departments',
                             'host': 'professors',
                             'path': ['professors', 'office_hours'],
                             'dropped': ['professor_id'],
                             'host_columns': ['id'],
                             'id_column': None,
                             'fields': {'id': 'id',
                                        'weekday': 'weekday',
                                        'starts': 'starts',
                                        'ends': 'ends'},
                             'scalar_column': None,
                             'pk': ['id'],
                             'identity': ['id'],
                             'columns': {'id': {'base': 'INTEGER',
                                                'is_array': False,
                                                'nullable': False},
                                         'professor_id': {'base': 'INTEGER',
                                                          'is_array': False,
                                                          'nullable': False},
                                         'weekday': {'base': 'INTEGER',
                                                     'is_array': False,
                                                     'nullable': False},
                                         'starts': {'base': 'TIME',
                                                    'is_array': False,
                                                    'nullable': False},
                                         'ends': {'base': 'TIME',
                                                  'is_array': False,
                                                  'nullable': False}}}},
 'relationships': [{'id': 'fk:professors.department_id->departments.id',
                    'child': 'professors',
                    'parent': 'departments',
                    'columns': ['department_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'NO ACTION',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:students.advisor_id->professors.id',
                    'child': 'students',
                    'parent': 'professors',
                    'columns': ['advisor_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'SET NULL',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:courses.department_id->departments.id',
                    'child': 'courses',
                    'parent': 'departments',
                    'columns': ['department_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:prerequisites.course_id->courses.id',
                    'child': 'prerequisites',
                    'parent': 'courses',
                    'columns': ['course_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:prerequisites.requires_id->courses.id',
                    'child': 'prerequisites',
                    'parent': 'courses',
                    'columns': ['requires_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'NO ACTION',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:sections.course_id->courses.id',
                    'child': 'sections',
                    'parent': 'courses',
                    'columns': ['course_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:sections.professor_id->professors.id',
                    'child': 'sections',
                    'parent': 'professors',
                    'columns': ['professor_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'SET NULL',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:enrollments.student_id->students.id',
                    'child': 'enrollments',
                    'parent': 'students',
                    'columns': ['student_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:enrollments.section_id->sections.id',
                    'child': 'enrollments',
                    'parent': 'sections',
                    'columns': ['section_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:office_hours.professor_id->professors.id',
                    'child': 'office_hours',
                    'parent': 'professors',
                    'columns': ['professor_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True}],
 'defaults': {'students': {'enrolled_on': {'kind': 'now', 'value': None}}},
 'unique': {'departments': [['name']],
            'professors': [['email']],
            'students': [['email']],
            'courses': [['code']],
            'sections': [['course_id', 'term']]}}


# --- Runtime of the generated ... (runtime elided) ...

# ---- per-table helpers (generated) ------------------------------------------

def insert_courses(db, values, session=None):
    # Mitigates:
    #   auto_increment:courses.id (CHANGED): EQ-AUTOINC
    #   pk:courses.id (CHANGED): EQ-ENTITY-UNIQ
    #   unique:courses.code (CHANGED): EQ-VALUE-UNIQ
    """INSERT INTO courses: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'courses', values, session)


def delete_courses(client, db, **match):
    # Mitigates:
    #   restrict_delete:prerequisites.requires_id->courses.id (CHANGED): EQ-RESTRICT
    #   cascade_delete:sections.course_id->courses.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM courses WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'courses', match, session)
    )


def update_courses(client, db, match, changes):
    """UPDATE courses SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'courses', match, changes, session
        ),
    )


def insert_departments(db, values, session=None):
    # Mitigates:
    #   auto_increment:departments.id (CHANGED): EQ-AUTOINC
    """INSERT INTO departments: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'departments', values, session)


def delete_departments(client, db, **match):
    # Mitigates:
    #   restrict_delete:professors.department_id->departments.id (CHANGED): EQ-RESTRICT
    #   cascade_delete:courses.department_id->departments.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM departments WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'departments', match, session)
    )


def update_departments(client, db, match, changes):
    """UPDATE departments SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'departments', match, changes, session
        ),
    )


def insert_enrollments(db, values, session=None):
    # Mitigates:
    #   pk:enrollments.student_id,section_id (CHANGED): EQ-ENTITY-UNIQ
    #   fk:enrollments.section_id->sections.id (CHANGED): EQ-REF-INTEGRITY
    #   cross_unique:enrollments.student_id,section_id (CHANGED): EQ-CROSS-UNIQ
    """INSERT INTO enrollments: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'enrollments', values, session)


def delete_enrollments(client, db, **match):
    """DELETE FROM enrollments WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'enrollments', match, session)
    )


def insert_office_hours(db, values, session=None):
    # Mitigates:
    #   auto_increment:office_hours.id (CHANGED): EQ-AUTOINC
    #   pk:office_hours.id (CHANGED): EQ-ENTITY-UNIQ
    """INSERT INTO office_hours: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'office_hours', values, session)


def delete_office_hours(client, db, **match):
    """DELETE FROM office_hours WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'office_hours', match, session)
    )


def insert_prerequisites(db, values, session=None):
    # Mitigates:
    #   pk:prerequisites.course_id,requires_id (CHANGED): EQ-ENTITY-UNIQ
    #   fk:prerequisites.requires_id->courses.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO prerequisites: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'prerequisites', values, session)


def delete_prerequisites(client, db, **match):
    """DELETE FROM prerequisites WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'prerequisites', match, session)
    )


def insert_professors(db, values, session=None):
    # Mitigates:
    #   auto_increment:professors.id (CHANGED): EQ-AUTOINC
    #   pk:professors.id (CHANGED): EQ-ENTITY-UNIQ
    #   unique:professors.email (CHANGED): EQ-VALUE-UNIQ
    """INSERT INTO professors: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'professors', values, session)


def delete_professors(client, db, **match):
    # Mitigates:
    #   set_null:students.advisor_id->professors.id (BROKEN): EQ-SET-NULL
    #   set_null:sections.professor_id->professors.id (BROKEN): EQ-SET-NULL
    """DELETE FROM professors WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'professors', match, session)
    )


def update_professors(client, db, match, changes):
    """UPDATE professors SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'professors', match, changes, session
        ),
    )


def insert_sections(db, values, session=None):
    # Mitigates:
    #   auto_increment:sections.id (CHANGED): EQ-AUTOINC
    #   pk:sections.id (CHANGED): EQ-ENTITY-UNIQ
    #   unique:sections.course_id,term (CHANGED): EQ-VALUE-UNIQ
    #   fk:sections.professor_id->professors.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO sections: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'sections', values, session)


def delete_sections(client, db, **match):
    # Mitigates:
    #   cascade_delete:enrollments.section_id->sections.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM sections WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'sections', match, session)
    )


def update_sections(client, db, match, changes):
    """UPDATE sections SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'sections', match, changes, session
        ),
    )


def insert_students(db, values, session=None):
    # Mitigates:
    #   auto_increment:students.id (CHANGED): EQ-AUTOINC
    #   default:students.enrolled_on (CHANGED): EQ-DEFAULT
    #   fk:students.advisor_id->professors.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO students: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'students', values, session)


def delete_students(client, db, **match):
    """DELETE FROM students WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'students', match, session)
    )


def update_students(client, db, match, changes):
    """UPDATE students SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'students', match, changes, session
        ),
    )
