# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Indexes: unique constraints and foreign-key equivalents."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def create_indexes(db):
    # unique:departments.name: unique
    db['departments'].create_index([['name', 1]], **{'name': 'uq_departments_name', 'unique': True})
    # unique:professors.email: unique; partial because parents without embedded rows have no such field
    db['departments'].create_index([['professors.email', 1]], **{
        'name': 'uq_departments_professors_email',
        'unique': True,
        'partialFilterExpression': {'professors.email': {'$exists': True}},
    })
    # unique:students.email: unique
    db['students'].create_index([['email', 1]], **{'name': 'uq_students_email', 'unique': True})
    # unique:courses.code: unique; partial because parents without embedded rows have no such field
    db['departments'].create_index([['courses.code', 1]], **{
        'name': 'uq_departments_courses_code',
        'unique': True,
        'partialFilterExpression': {'courses.code': {'$exists': True}},
    })
    # fk:students.advisor_id->professors.id: supports lookups along the foreign key
    db['students'].create_index([['advisor_id', 1]], **{'name': 'idx_students_advisor_id'})
    # fk:prerequisites.requires_id->courses.id: supports lookups along the foreign key
    db['departments'].create_index([['courses.prerequisites.requires_id', 1]], **{'name': 'idx_departments_courses_prerequisites_requires_id'})
    # fk:sections.professor_id->professors.id: supports lookups along the foreign key
    db['departments'].create_index([['courses.sections.professor_id', 1]], **{'name': 'idx_departments_courses_sections_professor_id'})
    # fk:enrollments.section_id->sections.id: supports lookups along the foreign key
    db['students'].create_index([['enrollments.section_id', 1]], **{'name': 'idx_students_enrollments_section_id'})
