# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Translated queries (each function takes a pymongo Database)."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def q1(db):
    """SELECT s.name, e.grade FROM students s JOIN enrollments e ON e.student_id = s.id WHERE e.grade = 'A'"""
    # q1: SELECT s.name, e.grade FROM students s JOIN enrollments e ON e.student_id = s.id WHERE e.grade = 'A'
    # columns: name, grade
    result = list(db['students'].aggregate([
            {'$replaceRoot': {'newRoot': {'s': '$$ROOT'}}},
            {'$unwind': {'path': '$s.enrollments', 'preserveNullAndEmptyArrays': False}},
            {'$match': {'s.enrollments.grade': 'A'}},
            {
                '$project': {
                    '_id': 0,
                    'name': {'$ifNull': ['$s.name', None]},
                    'grade': {'$ifNull': ['$s.enrollments.grade', None]},
                },
            },
        ]))
    return result

def q2(db):
    """SELECT d.name, COUNT(*) FROM departments d LEFT JOIN professors p ON p.department_id = d.id GROUP BY d.name"""
    # q2: SELECT d.name, COUNT(*) FROM departments d LEFT JOIN professors p ON p.department_id = d.id GROUP BY d.name
    # columns: name, count
    result = list(db['departments'].aggregate([
            {'$replaceRoot': {'newRoot': {'d': '$$ROOT'}}},
            {'$unwind': {'path': '$d.professors', 'preserveNullAndEmptyArrays': True}},
            {'$group': {'_id': {'g0': '$d.name'}, '__a0': {'$sum': 1}}},
            {
                '$addFields': {'name': {'$ifNull': ['$_id.g0', None]}, 'count': {'$ifNull': ['$__a0', None]}},
            },
            {'$project': {'_id': 0, 'name': 1, 'count': 1}},
        ]))
    return result

def q3(db):
    """SELECT AVG(gpa) FROM students"""
    # q3: SELECT AVG(gpa) FROM students
    # columns: avg
    result = list(db['students'].aggregate([
            {'$replaceRoot': {'newRoot': {'students': '$$ROOT'}}},
            {'$group': {'_id': None, '__a0': {'$avg': '$students.gpa'}}},
            {'$addFields': {'avg': {'$ifNull': ['$__a0', None]}}},
            {'$project': {'_id': 0, 'avg': 1}},
        ]))
    return result

def txn_t1(client, db):
    """Transaction t1: all-or-nothing across collections."""
    def body(session):
        # q4: INSERT INTO enrollments (student_id, section_id) VALUES (1, 1)
        db['students'].update_one({'_id': 1}, {'$push': {'enrollments': {'section_id': 1}}}, session=session)
        # q5: UPDATE sections SET room = 'R1' WHERE id = 1
        db['departments'].update_many({'courses.sections.id': 1, 'courses.sections': {'$exists': True}}, {'$set': {'courses.$[o0].sections.$[el].room': 'R1'}}, array_filters=[{'o0.sections': {'$exists': True}}, {'el.id': 1}], session=session)
    with client.start_session() as session:
        session.with_transaction(body)
