# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Collections with $jsonSchema validators."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def ensure_collection(db, name, options):
    """Create the collection, or update its validator when it already exists."""
    if name not in db.list_collection_names():
        db.create_collection(name, **{
            "validator": options["validator"],
            "validationLevel": options["validationLevel"],
            "validationAction": options["validationAction"],
        })
    else:
        db.command("collMod", name, **options)


def create_collections(db):
    # departments: SQL table departments; _id = departments.id
    ensure_collection(db, 'departments', {
        'validator': {
            '$and': [
                {
                    '$jsonSchema': {
                        'bsonType': 'object',
                        'required': ['name'],
                        'properties': {
                            '_id': {'bsonType': 'int'},
                            'name': {'bsonType': 'string'},
                            'budget': {'bsonType': 'decimal'},
                            'courses': {
                                'bsonType': 'array',
                                'items': {
                                    'bsonType': 'object',
                                    'required': ['id', 'code', 'title', 'credits'],
                                    'properties': {
                                        'id': {'bsonType': 'int'},
                                        'code': {'bsonType': 'string', 'maxLength': 10},
                                        'title': {'bsonType': 'string'},
                                        'credits': {'bsonType': 'int', 'minimum': 1, 'maximum': 6},
                                        'prerequisites': {
                                            'bsonType': 'array',
                                            'items': {
                                                'bsonType': 'object',
                                                'required': ['requires_id'],
                                                'properties': {'requires_id': {'bsonType': 'int'}},
                                                'additionalProperties': False,
                                            },
                                        },
                                        'sections': {
                                            'bsonType': 'array',
                                            'items': {
                                                'bsonType': 'object',
                                                'required': ['id', 'term'],
                                                'properties': {
                                                    'id': {'bsonType': 'int'},
                                                    'professor_id': {'bsonType': 'int'},
                                                    'term': {'bsonType': 'string', 'maxLength': 6},
                                                    'room': {'bsonType': 'string'},
                                                },
                                                'additionalProperties': False,
                                            },
                                        },
                                    },
                                    'additionalProperties': False,
                                },
                            },
                            'professors': {
                                'bsonType': 'array',
                                'items': {
                                    'bsonType': 'object',
                                    'required': ['id', 'name', 'email'],
                                    'properties': {
                                        'id': {'bsonType': 'int'},
                                        'name': {'bsonType': 'string'},
                                        'email': {'bsonType': 'string'},
                                        'office_hours': {
                                            'bsonType': 'array',
                                            'items': {
                                                'bsonType': 'object',
                                                'required': ['id', 'weekday', 'starts', 'ends'],
                                                'properties': {
                                                    'id': {'bsonType': 'int'},
                                                    'weekday': {'bsonType': 'int', 'minimum': 0, 'maximum': 6},
                                                    'starts': {'bsonType': 'string'},
                                                    'ends': {'bsonType': 'string'},
                                                },
                                                'additionalProperties': False,
                                            },
                                        },
                                    },
                                    'additionalProperties': False,
                                },
                            },
                        },
                        'additionalProperties': False,
                    },
                },
                {
                    '$expr': {
                        '$allElementsTrue': [
                            {
                                '$map': {
                                    'input': {'$ifNull': ['$courses', []]},
                                    'as': 'e1',
                                    'in': {
                                        '$allElementsTrue': [
                                            {
                                                '$map': {
                                                    'input': {'$ifNull': ['$$e1.prerequisites', []]},
                                                    'as': 'e2',
                                                    'in': {
                                                        '$or': [
                                                            {'$lte': ['$$e1.id', None]},
                                                            {'$lte': ['$$e2.requires_id', None]},
                                                            {'$ne': ['$$e1.id', '$$e2.requires_id']},
                                                        ],
                                                    },
                                                },
                                            },
                                        ],
                                    },
                                },
                            },
                        ],
                    },
                },
            ],
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # students: SQL table students; _id = students.id
    ensure_collection(db, 'students', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['name', 'email', 'enrolled_on'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'name': {'bsonType': 'string'},
                    'email': {'bsonType': 'string'},
                    'enrolled_on': {'bsonType': 'date'},
                    'advisor_id': {'bsonType': 'int'},
                    'gpa': {'bsonType': 'decimal', 'minimum': 0, 'maximum': 4},
                    'enrollments': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['section_id'],
                            'properties': {
                                'section_id': {'bsonType': 'int'},
                                'grade': {'bsonType': 'string', 'enum': ['A', 'B', 'C', 'D', 'F']},
                            },
                            'additionalProperties': False,
                        },
                    },
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
