"""Re-emit DDL from the parsed ``Schema`` (never from the raw user string) and whitelist it."""

from __future__ import annotations

import sqlglot
from sqlglot import exp

from schemashift.models.schema import ForeignKey, NormalizedType, Schema, Table


class UnsafeSqlError(Exception):
    """An expression contains something outside the sandbox whitelist."""


SAFE_FUNCTIONS = frozenset(
    {
        "upper",
        "lower",
        "abs",
        "length",
        "char_length",
        "coalesce",
        "round",
        "greatest",
        "least",
        "trim",
        "substring",
        "now",
        "current_timestamp",
        "current_date",
        "current_time",
        "gen_random_uuid",
        "uuid",
        "extract",
        "concat",
        "nullif",
        "floor",
        "ceil",
        "sum",
        "count",
        "avg",
        "min",
        "max",
        "cast",
    }
)
FORBIDDEN_PREFIXES = ("pg_", "information_schema", "dblink", "lo_", "set_config")


def func_name(node: exp.Expr) -> str:
    if isinstance(node, exp.Anonymous):
        return str(node.name).lower()
    sql_name = getattr(node, "sql_name", None)
    return str(sql_name()).lower() if callable(sql_name) else str(node.key).lower()


def assert_safe_expression(node: exp.Expr, schema: Schema | None = None) -> None:
    """Allow only pure expressions: whitelisted functions, no subqueries, no system catalogs."""
    for sub in node.walk():
        if isinstance(sub, (exp.Select, exp.Subquery, exp.Command, exp.Query)) and sub is not node:
            raise UnsafeSqlError(f"subqueries are not allowed: {sub.sql(dialect='postgres')}")
        if isinstance(sub, exp.Func) and not isinstance(
            sub, (exp.Binary, exp.Unary, exp.Connector)
        ):
            name = func_name(sub)
            if name not in SAFE_FUNCTIONS or name.startswith(FORBIDDEN_PREFIXES):
                raise UnsafeSqlError(f"function {name}() is not allowed in the sandbox")
        if isinstance(sub, exp.Table):
            if sub.args.get("db") or sub.args.get("catalog"):
                raise UnsafeSqlError(
                    f"qualified table {sub.sql(dialect='postgres')} is not allowed"
                )
            if schema is not None and str(sub.name).lower() not in schema.tables:
                raise UnsafeSqlError(f"unknown table {sub.name}")
        if isinstance(sub, exp.Identifier) and str(sub.name).lower().startswith(FORBIDDEN_PREFIXES):
            raise UnsafeSqlError(f"identifier {sub.name} is not allowed")


def assert_safe_sql(sql: str) -> exp.Expr:
    try:
        node = sqlglot.parse_one(sql, dialect="postgres")
    except sqlglot.errors.SqlglotError as exc:
        raise UnsafeSqlError(f"unparseable expression: {sql}") from exc
    assert_safe_expression(node)
    return node


def q(name: str) -> str:
    """Quote an identifier."""
    return '"' + name.replace('"', '""') + '"'


def type_sql(t: NormalizedType) -> str:
    base = t.base
    if base == "ENUM":
        text = q(t.enum_name or "")
    elif base == "DECIMAL":
        text = "NUMERIC" if t.precision is None else f"NUMERIC({t.precision},{t.scale or 0})"
    elif base == "FLOAT":
        text = "REAL"
    elif base == "DOUBLE":
        text = "DOUBLE PRECISION"
    elif base in ("VARCHAR", "CHAR"):
        text = f"{base}({t.length})" if t.length else base
    else:
        text = base
    return text + ("[]" if t.is_array else "")


def _column_sql(table: Table, schema: Schema) -> list[str]:
    out: list[str] = []
    for c in table.columns:
        parts = [q(c.name), type_sql(c.sql_type)]
        if c.is_identity:
            parts.append("GENERATED BY DEFAULT AS IDENTITY")
        if not c.nullable:
            parts.append("NOT NULL")
        if c.default is not None:
            assert_safe_sql(c.default.sql)
            parts.append(f"DEFAULT {c.default.sql}")
        out.append(" ".join(parts))
    return out


def fk_sql(table: Table, fk: ForeignKey, n: int) -> str:
    name = fk.name or f"fk_{table.name}_{n}"
    cols = ", ".join(q(c) for c in fk.columns)
    refs = ", ".join(q(c) for c in fk.ref_columns)
    text = (
        f"ALTER TABLE {q(table.name)} ADD CONSTRAINT {q(name)} FOREIGN KEY ({cols}) "
        f"REFERENCES {q(fk.ref_table)} ({refs}) ON DELETE {fk.on_delete} ON UPDATE {fk.on_update}"
    )
    return text + (" DEFERRABLE" if fk.deferrable else "")


def ddl_statements(schema: Schema) -> tuple[list[str], list[str]]:
    """``(statements, warnings)``: enums, tables, foreign keys, indexes. All names quoted."""
    stmts: list[str] = []
    warnings: list[str] = []
    for enum in schema.enums.values():
        values = ", ".join("'" + v.replace("'", "''") + "'" for v in enum.values)
        stmts.append(f"CREATE TYPE {q(enum.name)} AS ENUM ({values})")
    for table in schema.tables.values():
        body = _column_sql(table, schema)
        if table.primary_key:
            body.append(f"PRIMARY KEY ({', '.join(q(c) for c in table.primary_key.columns)})")
        for i, u in enumerate(table.uniques, 1):
            name = u.name or f"uq_{table.name}_{i}"
            body.append(f"CONSTRAINT {q(name)} UNIQUE ({', '.join(q(c) for c in u.columns)})")
        for i, ck in enumerate(table.checks, 1):
            try:
                assert_safe_sql(ck.expression_sql)
            except UnsafeSqlError as exc:
                warnings.append(f"CHECK on {table.name} skipped in the sandbox: {exc}")
                continue
            name = ck.name or f"ck_{table.name}_{i}"
            body.append(f"CONSTRAINT {q(name)} CHECK ({ck.expression_sql})")
        stmts.append(f"CREATE TABLE {q(table.name)} (\n  " + ",\n  ".join(body) + "\n)")
    for table in schema.tables.values():
        for n, fk in enumerate(table.foreign_keys, 1):
            if fk.ref_table in schema.tables and fk.ref_columns:
                stmts.append(fk_sql(table, fk, n))
    for table in schema.tables.values():
        for ix in table.indexes:
            text = (
                f"CREATE {'UNIQUE ' if ix.unique else ''}INDEX {q(ix.name)} ON {q(table.name)} "
                f"({', '.join(q(c) for c in ix.columns)})"
            )
            if ix.where_sql:
                try:
                    assert_safe_sql(ix.where_sql)
                except UnsafeSqlError as exc:
                    warnings.append(f"index {ix.name} skipped in the sandbox: {exc}")
                    continue
                text += f" WHERE {ix.where_sql}"
            stmts.append(text)
    return stmts, warnings
