// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Indexes: unique constraints and foreign-key equivalents.

// unique:branches.name: unique
db.getCollection("branches").createIndex({name: 1}, {name: "uq_branches_name", unique: true});

// unique:customers.email: unique
db.getCollection("customers").createIndex({email: 1}, {name: "uq_customers_email", unique: true});

// unique:customers.phone: unique; partial so that NULLs (absent fields) do not collide
db.getCollection("customers").createIndex({phone: 1}, {name: "uq_customers_phone", unique: true, partialFilterExpression: {phone: {$exists: true}}});

// unique:kyc_profiles.national_id: unique; partial because parents without embedded rows have no such field
db.getCollection("customers").createIndex({"kyc_profiles.national_id": 1}, {
  name: "uq_customers_kyc_profiles_national_id",
  unique: true,
  partialFilterExpression: {"kyc_profiles.national_id": {$exists: true}}
});

// unique:cards.number: unique; partial because parents without embedded rows have no such field
db.getCollection("accounts").createIndex({"cards.number": 1}, {
  name: "uq_accounts_cards_number",
  unique: true,
  partialFilterExpression: {"cards.number": {$exists: true}}
});

// fk:customers.home_branch_id->branches.id: supports lookups along the foreign key
db.getCollection("customers").createIndex({home_branch_id: 1}, {name: "idx_customers_home_branch_id"});

// fk:accounts.customer_id->customers.id: supports lookups along the foreign key
db.getCollection("accounts").createIndex({customer_id: 1}, {name: "idx_accounts_customer_id"});

// fk:accounts.branch_id->branches.id: supports lookups along the foreign key
db.getCollection("accounts").createIndex({branch_id: 1}, {name: "idx_accounts_branch_id"});

// fk:transactions.account_id->accounts.id: supports lookups along the foreign key
db.getCollection("transactions").createIndex({account_id: 1}, {name: "idx_transactions_account_id"});

// fk:beneficiaries.customer_id->customers.id: supports lookups along the foreign key
db.getCollection("accounts").createIndex({"beneficiaries.customer_id": 1}, {name: "idx_accounts_beneficiaries_customer_id"});
