// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Translated queries. Output field names match the SQL column aliases.

// q1: SELECT a.id, COUNT(*) AS n, SUM(t.amount) AS total FROM accounts a JOIN transactions t ON t.account_id = a.id GROUP BY a.id
// columns: id, n, total
const q1 = db.getCollection("accounts").aggregate([
  {$replaceRoot: {newRoot: {a: "$$ROOT"}}},
  {$lookup: {from: "transactions", localField: "a._id", foreignField: "account_id", as: "t"}},
  {$unwind: {path: "$t", preserveNullAndEmptyArrays: false}},
  {
    $group: {
      _id: {g0: "$a._id"},
      __a0: {$sum: 1},
      __a1: {$sum: "$t.amount"},
      __a1_n: {$sum: {$cond: [{$gt: ["$t.amount", null]}, 1, 0]}}
    }
  },
  {
    $addFields: {
      id: {$ifNull: ["$_id.g0", null]},
      n: {$ifNull: ["$__a0", null]},
      total: {$ifNull: [{$cond: [{$eq: ["$__a1_n", 0]}, null, "$__a1"]}, null]}
    }
  },
  {$project: {_id: 0, id: 1, n: 1, total: 1}}
]).toArray();

// q2: SELECT c.full_name, k.national_id FROM customers c JOIN kyc_profiles k ON k.customer_id = c.id
// columns: full_name, national_id
const q2 = db.getCollection("customers").aggregate([
  {$replaceRoot: {newRoot: {c: "$$ROOT"}}},
  {$match: {"c.kyc_profiles": {$exists: true}}},
  {
    $project: {
      _id: 0,
      full_name: {$ifNull: ["$c.full_name", null]},
      national_id: {$ifNull: ["$c.kyc_profiles.national_id", null]}
    }
  }
]).toArray();

// q3: SELECT c.full_name, a.balance FROM customers c LEFT JOIN accounts a ON a.customer_id = c.id
// columns: full_name, balance
const q3 = db.getCollection("customers").aggregate([
  {$replaceRoot: {newRoot: {c: "$$ROOT"}}},
  {$lookup: {from: "accounts", localField: "c._id", foreignField: "customer_id", as: "a"}},
  {$unwind: {path: "$a", preserveNullAndEmptyArrays: true}},
  {
    $project: {
      _id: 0,
      full_name: {$ifNull: ["$c.full_name", null]},
      balance: {$ifNull: ["$a.balance", null]}
    }
  }
]).toArray();

// q4: SELECT SUM(balance) FROM accounts
// columns: sum
const q4 = db.getCollection("accounts").aggregate([
  {$replaceRoot: {newRoot: {accounts: "$$ROOT"}}},
  {
    $group: {
      _id: null,
      __a0: {$sum: "$accounts.balance"},
      __a0_n: {$sum: {$cond: [{$gt: ["$accounts.balance", null]}, 1, 0]}}
    }
  },
  {$addFields: {sum: {$ifNull: [{$cond: [{$eq: ["$__a0_n", 0]}, null, "$__a0"]}, null]}}},
  {$project: {_id: 0, sum: 1}}
]).toArray();

// ---- transaction t1: all-or-nothing across collections
{
  const session = db.getMongo().startSession();
  session.withTransaction(() => {
    const sdb = session.getDatabase(db.getName());
    // q5: UPDATE accounts SET balance = balance - 100 WHERE id = 1
    sdb.getCollection("accounts").updateMany({_id: 1}, [{$set: {balance: {$subtract: ["$balance", 100]}}}]);
    // q6: UPDATE accounts SET balance = balance + 100 WHERE id = 2
    sdb.getCollection("accounts").updateMany({_id: 2}, [{$set: {balance: {$add: ["$balance", 100]}}}]);
    // q7: INSERT INTO transactions (account_id, kind, amount) VALUES (1, 'transfer', 100)
    // note: transactions.id is auto-generated: allocated by the insert helper (counter or ObjectId), not by this statement
    sdb.getCollection("transactions").insertOne({account_id: 1, kind: "transfer", amount: NumberDecimal("100"), created_at: new Date()});
  });
  session.endSession();
}
