# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z
# Application-level enforcement helpers. MongoDB has no foreign keys, cascades,
# defaults or sequences: these functions re-create the guarantees marked
# CHANGED or BROKEN by the equivalence checker.
# Requires migrate.py next to this file (or schemashift installed).

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from bson import ObjectId

try:
    from schemashift.codegen.runtime_migrate import convert_value, row_to_doc
except ImportError:  # generated deployment: migrate.py sits next to helpers.py
    from migrate import convert_value, row_to_doc  # type: ignore[import-not-found,no-redef]

PLAN = {'options': {'uuid_as': 'binary', 'preserve_integer_ids': False},
 'roots': ['tags', 'users'],
 'tables': {'users': {'kind': 'root',
                      'collection': 'users',
                      'host': None,
                      'path': [],
                      'dropped': [],
                      'host_columns': [],
                      'id_column': 'id',
                      'fields': {'id': '_id',
                                 'username': 'username',
                                 'email': 'email',
                                 'bio': 'bio',
                                 'created_at': 'created_at'},
                      'scalar_column': None,
                      'pk': ['id'],
                      'identity': ['id'],
                      'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                  'username': {'base': 'VARCHAR',
                                               'is_array': False,
                                               'nullable': False},
                                  'email': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'bio': {'base': 'TEXT', 'is_array': False, 'nullable': True},
                                  'created_at': {'base': 'TIMESTAMPTZ',
                                                 'is_array': False,
                                                 'nullable': False}}},
            'posts': {'kind': 'array',
                      'collection': 'users',
                      'host': 'users',
                      'path': ['posts'],
                      'dropped': ['author_id'],
                      'host_columns': ['id'],
                      'id_column': None,
                      'fields': {'id': 'id',
                                 'title': 'title',
                                 'body': 'body',
                                 'status': 'status',
                                 'published_at': 'published_at'},
                      'scalar_column': None,
                      'pk': ['id'],
                      'identity': ['id'],
                      'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                  'author_id': {'base': 'INTEGER',
                                                'is_array': False,
                                                'nullable': False},
                                  'title': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'body': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'status': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'published_at': {'base': 'TIMESTAMPTZ',
                                                   'is_array': False,
                                                   'nullable': True}}},
            'comments': {'kind': 'array',
                         'collection': 'users',
                         'host': 'posts',
                         'path': ['posts', 'comments'],
                         'dropped': ['post_id'],
                         'host_columns': ['id'],
                         'id_column': None,
                         'fields': {'id': 'id',
                                    'author_id': 'author_id',
                                    'parent_comment_id': 'parent_comment_id',
                                    'body': 'body',
                                    'created_at': 'created_at'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'post_id': {'base': 'INTEGER',
                                                 'is_array': False,
                                                 'nullable': False},
                                     'author_id': {'base': 'INTEGER',
                                                   'is_array': False,
                                                   'nullable': False},
                                     'parent_comment_id': {'base': 'INTEGER',
                                                           'is_array': False,
                                                           'nullable': True},
                                     'body': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                     'created_at': {'base': 'TIMESTAMPTZ',
                                                    'is_array': False,
                                                    'nullable': False}}},
            'tags': {'kind': 'root',
                     'collection': 'tags',
                     'host': None,
                     'path': [],
                     'dropped': [],
                     'host_columns': [],
                     'id_column': 'id',
                     'fields': {'id': '_id', 'name': 'name'},
                     'scalar_column': None,
                     'pk': ['id'],
                     'identity': ['id'],
                     'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                 'name': {'base': 'VARCHAR',
                                          'is_array': False,
                                          'nullable': False}}},
            'post_tags': {'kind': 'ref_scalars',
                          'collection': 'tags',
                          'host': 'tags',
                          'path': ['post_ids'],
                          'dropped': ['tag_id'],
                          'host_columns': ['id'],
                          'id_column': None,
                          'fields': {},
                          'scalar_column': 'post_id',
                          'pk': ['post_id', 'tag_id'],
                          'identity': [],
                          'columns': {'post_id': {'base': 'INTEGER',
                                                  'is_array': False,
                                                  'nullable': False},
                                      'tag_id': {'base': 'INTEGER',
                                                 'is_array': False,
                                                 'nullable': False}}}},
 'relationships': [{'id': 'fk:posts.author_id->users.id',
                    'child': 'posts',
                    'parent': 'users',
                    'columns': ['author_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:comments.post_id->posts.id',
                    'child': 'comments',
                    'parent': 'posts',
                    'columns': ['post_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:comments.author_id->users.id',
                    'child': 'comments',
                    'parent': 'users',
                    'columns': ['author_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:comments.parent_comment_id->comments.id',
                    'child': 'comments',
                    'parent': 'comments',
                    'columns': ['parent_comment_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:post_tags.post_id->posts.id',
                    'child': 'post_tags',
                    'parent': 'posts',
                    'columns': ['post_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:post_tags.tag_id->tags.id',
                    'child': 'post_tags',
                    'parent': 'tags',
                    'columns': ['tag_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True}],
 'defaults': {'users': {'created_at': {'kind': 'now', 'value': None}},
              'posts': {'status': {'kind': 'literal', 'value': 'draft'}},
              'comments': {'created_at': {'kind': 'now', 'value': None}}},
 'unique': {'users': [['username'], ['email']], 'tags': [['name']]}}


# --- Runtime of the generated ... (runtime elided) ...

# ---- per-table helpers (generated) ------------------------------------------

def insert_comments(db, values, session=None):
    # Mitigates:
    #   auto_increment:comments.id (CHANGED): EQ-AUTOINC
    #   default:comments.created_at (CHANGED): EQ-DEFAULT
    #   pk:comments.id (CHANGED): EQ-ENTITY-UNIQ
    #   fk:comments.author_id->users.id (CHANGED): EQ-REF-INTEGRITY
    #   fk:comments.parent_comment_id->comments.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO comments: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'comments', values, session)


def delete_comments(client, db, **match):
    # Mitigates:
    #   cascade_delete:comments.parent_comment_id->comments.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM comments WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'comments', match, session)
    )


def update_comments(client, db, match, changes):
    """UPDATE comments SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'comments', match, changes, session
        ),
    )


def insert_post_tags(db, values, session=None):
    # Mitigates:
    #   pk:post_tags.post_id,tag_id (CHANGED): EQ-ENTITY-UNIQ
    #   fk:post_tags.post_id->posts.id (CHANGED): EQ-REF-INTEGRITY
    #   cross_unique:post_tags.post_id,tag_id (BROKEN): EQ-CROSS-UNIQ
    """INSERT INTO post_tags: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'post_tags', values, session)


def delete_post_tags(client, db, **match):
    """DELETE FROM post_tags WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'post_tags', match, session)
    )


def insert_posts(db, values, session=None):
    # Mitigates:
    #   auto_increment:posts.id (CHANGED): EQ-AUTOINC
    #   default:posts.status (CHANGED): EQ-DEFAULT
    #   pk:posts.id (CHANGED): EQ-ENTITY-UNIQ
    """INSERT INTO posts: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'posts', values, session)


def delete_posts(client, db, **match):
    # Mitigates:
    #   cascade_delete:comments.post_id->posts.id (BROKEN): EQ-CASCADE-DEL
    #   cascade_delete:post_tags.post_id->posts.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM posts WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'posts', match, session)
    )


def update_posts(client, db, match, changes):
    """UPDATE posts SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'posts', match, changes, session
        ),
    )


def insert_tags(db, values, session=None):
    # Mitigates:
    #   auto_increment:tags.id (CHANGED): EQ-AUTOINC
    """INSERT INTO tags: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'tags', values, session)


def delete_tags(client, db, **match):
    """DELETE FROM tags WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'tags', match, session)
    )


def update_tags(client, db, match, changes):
    """UPDATE tags SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'tags', match, changes, session
        ),
    )


def insert_users(db, values, session=None):
    # Mitigates:
    #   auto_increment:users.id (CHANGED): EQ-AUTOINC
    #   default:users.created_at (CHANGED): EQ-DEFAULT
    """INSERT INTO users: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'users', values, session)


def delete_users(client, db, **match):
    # Mitigates:
    #   cascade_delete:posts.author_id->users.id (BROKEN): EQ-CASCADE-DEL
    #   cascade_delete:comments.author_id->users.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM users WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'users', match, session)
    )


def update_users(client, db, match, changes):
    """UPDATE users SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'users', match, changes, session
        ),
    )
