# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Indexes: unique constraints and foreign-key equivalents."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def create_indexes(db):
    # unique:users.username: unique
    db['users'].create_index([['username', 1]], **{'name': 'uq_users_username', 'unique': True})
    # unique:users.email: unique
    db['users'].create_index([['email', 1]], **{'name': 'uq_users_email', 'unique': True})
    # unique:tags.name: unique
    db['tags'].create_index([['name', 1]], **{'name': 'uq_tags_name', 'unique': True})
    # fk:comments.author_id->users.id: supports lookups along the foreign key
    db['users'].create_index([['posts.comments.author_id', 1]], **{'name': 'idx_users_posts_comments_author_id'})
    # fk:comments.parent_comment_id->comments.id: supports lookups along the foreign key
    db['users'].create_index([['posts.comments.parent_comment_id', 1]], **{'name': 'idx_users_posts_comments_parent_comment_id'})
    # m2n:post_tags: multikey index for reverse lookups of the reference array
    db['tags'].create_index([['post_ids', 1]], **{'name': 'idx_tags_post_ids'})
