# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z
# Data migration PostgreSQL -> MongoDB: reads each table, builds the nested
# documents of the placement plan and upserts them in batches of 1000
# (idempotent, by _id).
# Usage: python migrate.py --source postgresql://... --target mongodb://...
#        --database mydb

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import uuid
from datetime import UTC, date, datetime, timedelta
from typing import Any

import psycopg
from bson import Binary, Decimal128, ObjectId
from psycopg import sql
from psycopg.rows import dict_row
from pymongo import ReplaceOne

PLAN = {'options': {'uuid_as': 'binary', 'preserve_integer_ids': False},
 'roots': ['tags', 'users'],
 'tables': {'users': {'kind': 'root',
                      'collection': 'users',
                      'host': None,
                      'path': [],
                      'dropped': [],
                      'host_columns': [],
                      'id_column': 'id',
                      'fields': {'id': '_id',
                                 'username': 'username',
                                 'email': 'email',
                                 'bio': 'bio',
                                 'created_at': 'created_at'},
                      'scalar_column': None,
                      'pk': ['id'],
                      'identity': ['id'],
                      'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                  'username': {'base': 'VARCHAR',
                                               'is_array': False,
                                               'nullable': False},
                                  'email': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'bio': {'base': 'TEXT', 'is_array': False, 'nullable': True},
                                  'created_at': {'base': 'TIMESTAMPTZ',
                                                 'is_array': False,
                                                 'nullable': False}}},
            'posts': {'kind': 'array',
                      'collection': 'users',
                      'host': 'users',
                      'path': ['posts'],
                      'dropped': ['author_id'],
                      'host_columns': ['id'],
                      'id_column': None,
                      'fields': {'id': 'id',
                                 'title': 'title',
                                 'body': 'body',
                                 'status': 'status',
                                 'published_at': 'published_at'},
                      'scalar_column': None,
                      'pk': ['id'],
                      'identity': ['id'],
                      'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                  'author_id': {'base': 'INTEGER',
                                                'is_array': False,
                                                'nullable': False},
                                  'title': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'body': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'status': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                  'published_at': {'base': 'TIMESTAMPTZ',
                                                   'is_array': False,
                                                   'nullable': True}}},
            'comments': {'kind': 'array',
                         'collection': 'users',
                         'host': 'posts',
                         'path': ['posts', 'comments'],
                         'dropped': ['post_id'],
                         'host_columns': ['id'],
                         'id_column': None,
                         'fields': {'id': 'id',
                                    'author_id': 'author_id',
                                    'parent_comment_id': 'parent_comment_id',
                                    'body': 'body',
                                    'created_at': 'created_at'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'post_id': {'base': 'INTEGER',
                                                 'is_array': False,
                                                 'nullable': False},
                                     'author_id': {'base': 'INTEGER',
                                                   'is_array': False,
                                                   'nullable': False},
                                     'parent_comment_id': {'base': 'INTEGER',
                                                           'is_array': False,
                                                           'nullable': True},
                                     'body': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                     'created_at': {'base': 'TIMESTAMPTZ',
                                                    'is_array': False,
                                                    'nullable': False}}},
            'tags': {'kind': 'root',
                     'collection': 'tags',
                     'host': None,
                     'path': [],
                     'dropped': [],
                     'host_columns': [],
                     'id_column': 'id',
                     'fields': {'id': '_id', 'name': 'name'},
                     'scalar_column': None,
                     'pk': ['id'],
                     'identity': ['id'],
                     'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                 'name': {'base': 'VARCHAR',
                                          'is_array': False,
                                          'nullable': False}}},
            'post_tags': {'kind': 'ref_scalars',
                          'collection': 'tags',
                          'host': 'tags',
                          'path': ['post_ids'],
                          'dropped': ['tag_id'],
                          'host_columns': ['id'],
                          'id_column': None,
                          'fields': {},
                          'scalar_column': 'post_id',
                          'pk': ['post_id', 'tag_id'],
                          'identity': [],
                          'columns': {'post_id': {'base': 'INTEGER',
                                                  'is_array': False,
                                                  'nullable': False},
                                      'tag_id': {'base': 'INTEGER',
                                                 'is_array': False,
                                                 'nullable': False}}}}}


# --- Runtime of the generated ... (runtime elided) ...

