# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Translated queries (each function takes a pymongo Database)."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def q1(db):
    """SELECT p.title, u.username FROM posts p JOIN users u ON p.author_id = u.id WHERE p.status = 'published' ORDER BY p.id DESC LIMIT 10"""
    # q1: SELECT p.title, u.username FROM posts p JOIN users u ON p.author_id = u.id WHERE p.status = 'published' ORDER BY p.id DESC LIMIT 10
    # columns: title, username
    result = list(db['users'].aggregate([
            {'$replaceRoot': {'newRoot': {'_users': '$$ROOT'}}},
            {'$unwind': {'path': '$_users.posts', 'preserveNullAndEmptyArrays': False}},
            {'$match': {'_users.posts.status': 'published'}},
            {'$addFields': {'_n0': {'$cond': [{'$lte': ['$_users.posts.id', None]}, 1, 0]}}},
            {'$sort': {'_n0': -1, '_users.posts.id': -1}},
            {'$limit': 10},
            {
                '$project': {
                    '_id': 0,
                    'title': {'$ifNull': ['$_users.posts.title', None]},
                    'username': {'$ifNull': ['$_users.username', None]},
                },
            },
        ]))
    return result

def q2(db):
    """SELECT p.title, COUNT(*) AS comment_count FROM posts p LEFT JOIN comments c ON c.post_id = p.id GROUP BY p.title"""
    # q2: SELECT p.title, COUNT(*) AS comment_count FROM posts p LEFT JOIN comments c ON c.post_id = p.id GROUP BY p.title
    # columns: title, comment_count
    result = list(db['users'].aggregate([
            {'$replaceRoot': {'newRoot': {'_users': '$$ROOT'}}},
            {'$unwind': {'path': '$_users.posts', 'preserveNullAndEmptyArrays': False}},
            {'$unwind': {'path': '$_users.posts.comments', 'preserveNullAndEmptyArrays': True}},
            {'$group': {'_id': {'g0': '$_users.posts.title'}, '__a0': {'$sum': 1}}},
            {
                '$addFields': {'title': {'$ifNull': ['$_id.g0', None]}, 'comment_count': {'$ifNull': ['$__a0', None]}},
            },
            {'$project': {'_id': 0, 'title': 1, 'comment_count': 1}},
        ]))
    return result

def q3(db):
    """SELECT t.name, COUNT(*) AS uses FROM tags t JOIN post_tags pt ON pt.tag_id = t.id GROUP BY t.name ORDER BY uses DESC"""
    # q3: SELECT t.name, COUNT(*) AS uses FROM tags t JOIN post_tags pt ON pt.tag_id = t.id GROUP BY t.name ORDER BY uses DESC
    # columns: name, uses
    result = list(db['tags'].aggregate([
            {'$replaceRoot': {'newRoot': {'t': '$$ROOT'}}},
            {'$unwind': {'path': '$t.post_ids', 'preserveNullAndEmptyArrays': False}},
            {'$group': {'_id': {'g0': '$t.name'}, '__a0': {'$sum': 1}}},
            {'$addFields': {'name': {'$ifNull': ['$_id.g0', None]}, 'uses': {'$ifNull': ['$__a0', None]}}},
            {'$addFields': {'_n0': {'$cond': [{'$lte': ['$uses', None]}, 1, 0]}}},
            {'$sort': {'_n0': -1, 'uses': -1}},
            {'$project': {'_id': 0, 'name': 1, 'uses': 1}},
        ]))
    return result

def q4(db):
    """INSERT INTO comments (post_id, author_id, body) VALUES (1, 1, 'Nice post')"""
    # q4: INSERT INTO comments (post_id, author_id, body) VALUES (1, 1, 'Nice post')
    # note: comments.id is auto-generated: allocated by the insert helper (counter or ObjectId), not by this statement
    db['users'].update_one({'posts.id': 1}, {
            '$push': {
                'posts.$[h].comments': {'author_id': 1, 'body': 'Nice post', 'created_at': datetime.now(timezone.utc)},
            },
        }, array_filters=[{'h.id': 1}])
