# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Collections with $jsonSchema validators."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def ensure_collection(db, name, options):
    """Create the collection, or update its validator when it already exists."""
    if name not in db.list_collection_names():
        db.create_collection(name, **{
            "validator": options["validator"],
            "validationLevel": options["validationLevel"],
            "validationAction": options["validationAction"],
        })
    else:
        db.command("collMod", name, **options)


def create_collections(db):
    # tags: SQL table tags; _id = tags.id
    ensure_collection(db, 'tags', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['name'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'name': {'bsonType': 'string', 'maxLength': 30},
                    'post_ids': {'bsonType': 'array', 'items': {'bsonType': 'int'}, 'uniqueItems': True},
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # users: SQL table users; _id = users.id
    ensure_collection(db, 'users', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['username', 'email', 'created_at'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'username': {'bsonType': 'string', 'maxLength': 30},
                    'email': {'bsonType': 'string'},
                    'bio': {'bsonType': 'string'},
                    'created_at': {'bsonType': 'date'},
                    'posts': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['id', 'title', 'body', 'status'],
                            'properties': {
                                'id': {'bsonType': 'int'},
                                'title': {'bsonType': 'string'},
                                'body': {'bsonType': 'string'},
                                'status': {'bsonType': 'string', 'enum': ['draft', 'published']},
                                'published_at': {'bsonType': 'date'},
                                'comments': {
                                    'bsonType': 'array',
                                    'items': {
                                        'bsonType': 'object',
                                        'required': ['id', 'author_id', 'body', 'created_at'],
                                        'properties': {
                                            'id': {'bsonType': 'int'},
                                            'author_id': {'bsonType': 'int'},
                                            'parent_comment_id': {'bsonType': 'int'},
                                            'body': {'bsonType': 'string'},
                                            'created_at': {'bsonType': 'date'},
                                        },
                                        'additionalProperties': False,
                                    },
                                },
                            },
                            'additionalProperties': False,
                        },
                    },
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
