// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Collections with $jsonSchema validators (validationLevel strict).

function ensureCollection(name, options) {
  if (db.getCollectionInfos({ name: name }).length === 0) {
    db.createCollection(name, options);
  } else {
    db.runCommand(Object.assign({ collMod: name }, options));
  }
}

// tags: SQL table tags; _id = tags.id
ensureCollection("tags", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: ["name"],
      properties: {
        _id: {bsonType: "int"},
        name: {bsonType: "string", maxLength: 30},
        post_ids: {bsonType: "array", items: {bsonType: "int"}, uniqueItems: true}
      },
      additionalProperties: false
    }
  },
  validationLevel: "strict",
  validationAction: "error"
});

// users: SQL table users; _id = users.id
ensureCollection("users", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: ["username", "email", "created_at"],
      properties: {
        _id: {bsonType: "int"},
        username: {bsonType: "string", maxLength: 30},
        email: {bsonType: "string"},
        bio: {bsonType: "string"},
        created_at: {bsonType: "date"},
        posts: {
          bsonType: "array",
          items: {
            bsonType: "object",
            required: ["id", "title", "body", "status"],
            properties: {
              id: {bsonType: "int"},
              title: {bsonType: "string"},
              body: {bsonType: "string"},
              status: {bsonType: "string", enum: ["draft", "published"]},
              published_at: {bsonType: "date"},
              comments: {
                bsonType: "array",
                items: {
                  bsonType: "object",
                  required: ["id", "author_id", "body", "created_at"],
                  properties: {
                    id: {bsonType: "int"},
                    author_id: {bsonType: "int"},
                    parent_comment_id: {bsonType: "int"},
                    body: {bsonType: "string"},
                    created_at: {bsonType: "date"}
                  },
                  additionalProperties: false
                }
              }
            },
            additionalProperties: false
          }
        }
      },
      additionalProperties: false
    }
  },
  validationLevel: "strict",
  validationAction: "error"
});
