// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Indexes: unique constraints and foreign-key equivalents.

// unique:users.username: unique
db.getCollection("users").createIndex({username: 1}, {name: "uq_users_username", unique: true});

// unique:users.email: unique
db.getCollection("users").createIndex({email: 1}, {name: "uq_users_email", unique: true});

// unique:tags.name: unique
db.getCollection("tags").createIndex({name: 1}, {name: "uq_tags_name", unique: true});

// fk:comments.author_id->users.id: supports lookups along the foreign key
db.getCollection("users").createIndex({"posts.comments.author_id": 1}, {name: "idx_users_posts_comments_author_id"});

// fk:comments.parent_comment_id->comments.id: supports lookups along the foreign key
db.getCollection("users").createIndex({"posts.comments.parent_comment_id": 1}, {name: "idx_users_posts_comments_parent_comment_id"});

// m2n:post_tags: multikey index for reverse lookups of the reference array
db.getCollection("tags").createIndex({post_ids: 1}, {name: "idx_tags_post_ids"});
