// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Translated queries. Output field names match the SQL column aliases.

// q1: SELECT p.title, u.username FROM posts p JOIN users u ON p.author_id = u.id WHERE p.status = 'published' ORDER BY p.id DESC LIMIT 10
// columns: title, username
const q1 = db.getCollection("users").aggregate([
  {$replaceRoot: {newRoot: {_users: "$$ROOT"}}},
  {$unwind: {path: "$_users.posts", preserveNullAndEmptyArrays: false}},
  {$match: {"_users.posts.status": "published"}},
  {$addFields: {_n0: {$cond: [{$lte: ["$_users.posts.id", null]}, 1, 0]}}},
  {$sort: {_n0: -1, "_users.posts.id": -1}},
  {$limit: 10},
  {
    $project: {
      _id: 0,
      title: {$ifNull: ["$_users.posts.title", null]},
      username: {$ifNull: ["$_users.username", null]}
    }
  }
]).toArray();

// q2: SELECT p.title, COUNT(*) AS comment_count FROM posts p LEFT JOIN comments c ON c.post_id = p.id GROUP BY p.title
// columns: title, comment_count
const q2 = db.getCollection("users").aggregate([
  {$replaceRoot: {newRoot: {_users: "$$ROOT"}}},
  {$unwind: {path: "$_users.posts", preserveNullAndEmptyArrays: false}},
  {$unwind: {path: "$_users.posts.comments", preserveNullAndEmptyArrays: true}},
  {$group: {_id: {g0: "$_users.posts.title"}, __a0: {$sum: 1}}},
  {$addFields: {title: {$ifNull: ["$_id.g0", null]}, comment_count: {$ifNull: ["$__a0", null]}}},
  {$project: {_id: 0, title: 1, comment_count: 1}}
]).toArray();

// q3: SELECT t.name, COUNT(*) AS uses FROM tags t JOIN post_tags pt ON pt.tag_id = t.id GROUP BY t.name ORDER BY uses DESC
// columns: name, uses
const q3 = db.getCollection("tags").aggregate([
  {$replaceRoot: {newRoot: {t: "$$ROOT"}}},
  {$unwind: {path: "$t.post_ids", preserveNullAndEmptyArrays: false}},
  {$group: {_id: {g0: "$t.name"}, __a0: {$sum: 1}}},
  {$addFields: {name: {$ifNull: ["$_id.g0", null]}, uses: {$ifNull: ["$__a0", null]}}},
  {$addFields: {_n0: {$cond: [{$lte: ["$uses", null]}, 1, 0]}}},
  {$sort: {_n0: -1, uses: -1}},
  {$project: {_id: 0, name: 1, uses: 1}}
]).toArray();

// q4: INSERT INTO comments (post_id, author_id, body) VALUES (1, 1, 'Nice post')
// note: comments.id is auto-generated: allocated by the insert helper (counter or ObjectId), not by this statement
db.getCollection("users").updateOne({"posts.id": 1}, {$push: {"posts.$[h].comments": {author_id: 1, body: "Nice post", created_at: new Date()}}}, {arrayFilters: [{"h.id": 1}]});
