/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Endpoint
         * @description Run every pure compiler stage. Nothing is stored and no SQL is executed.
         */
        post: operations["compile_endpoint_api_v1_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run */
        get: operations["export_run_api_v1_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_api_v1_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample */
        get: operations["get_sample_api_v1_samples__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIOpinion */
        AIOpinion: {
            /**
             * Source
             * @enum {string}
             */
            source: "anthropic" | "mock" | "unavailable";
            /** Available */
            available: boolean;
            suggestion?: components["schemas"]["AISuggestion"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * AISuggestion
         * @description The LLM's advisory opinion (never overrides the optimizer).
         */
        AISuggestion: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "EMBED" | "REFERENCE";
            /** Confidence */
            confidence: number;
            /** Justification */
            justification: string;
        };
        /**
         * AccessHint
         * @description User supplied overrides for one relationship (all optional).
         */
        AccessHint: {
            /** Child Independent Access */
            child_independent_access?: number | null;
            /** Read Together Ratio */
            read_together_ratio?: number | null;
            /** Child Write Frequency */
            child_write_frequency?: ("low" | "med" | "high") | null;
            /** Estimated Child Count Per Parent */
            estimated_child_count_per_parent?: number | null;
        };
        /** CompileOptions */
        CompileOptions: {
            /**
             * Target Mongo Version
             * @default 7.0
             */
            target_mongo_version?: string;
            /**
             * Transactions Available
             * @default true
             */
            transactions_available?: boolean;
            /**
             * Preserve Integer Ids
             * @default false
             */
            preserve_integer_ids?: boolean;
            /**
             * Uuid As
             * @default binary
             * @enum {string}
             */
            uuid_as?: "binary" | "string";
            /**
             * Rows Per Table
             * @default 50
             */
            rows_per_table?: number;
            /**
             * Relationship Overrides
             * @default {}
             */
            relationship_overrides?: {
                [key: string]: "EMBED" | "REFERENCE" | "REF_ARRAY";
            };
            /**
             * Access Hints
             * @default {}
             */
            access_hints?: {
                [key: string]: components["schemas"]["AccessHint"];
            };
        };
        /** CompileRequest */
        CompileRequest: {
            /** Schema Sql */
            schema_sql: string;
            /**
             * Queries Sql
             * @default
             */
            queries_sql?: string;
            /**
             * Seed Sql
             * @default
             */
            seed_sql?: string;
            /**
             * @default {
             *       "target_mongo_version": "7.0",
             *       "transactions_available": true,
             *       "preserve_integer_ids": false,
             *       "uuid_as": "binary",
             *       "rows_per_table": 50,
             *       "relationship_overrides": {},
             *       "access_hints": {}
             *     }
             */
            options?: components["schemas"]["CompileOptions"];
        };
        /** CompileResponse */
        CompileResponse: {
            /**
             * Overall Verdict
             * @enum {string}
             */
            overall_verdict: "SAFE" | "CHANGED" | "BROKEN";
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Has Errors */
            has_errors: boolean;
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Queries Line Offset */
            queries_line_offset: number;
            /** Ir Text */
            ir_text: string;
            /** Ir Node Count */
            ir_node_count: number;
            /** Verdicts */
            verdicts: components["schemas"]["Verdict"][];
            /** Initial Counts */
            initial_counts: {
                [key: string]: number;
            };
            /** Changed By Placement */
            changed_by_placement: components["schemas"]["PlacementChange"][];
            /** Plan */
            plan: components["schemas"]["PlacementDecision"][];
            /** Plan Warnings */
            plan_warnings: string[];
            /** Graph Nodes */
            graph_nodes: components["schemas"]["GraphNode"][];
            /** Graph Edges */
            graph_edges: components["schemas"]["GraphEdge"][];
            /** Ai Enabled */
            ai_enabled: boolean;
            /** Generated */
            generated: components["schemas"]["GeneratedFile"][];
            /** Queries */
            queries: components["schemas"]["QueryTranslation"][];
            /** Untranslated Checks */
            untranslated_checks: components["schemas"]["UntranslatedCheckDTO"][];
            /** Warnings */
            warnings: string[];
        };
        /**
         * ConditionTrace
         * @description One condition a rule evaluated and its result (the UI's "Why?" view).
         */
        ConditionTrace: {
            /** Condition */
            condition: string;
            /** Result */
            result: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** Diagnostic */
        Diagnostic: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
            /** Code */
            code: string;
            /** Message */
            message: string;
            location?: components["schemas"]["SourceSpan"] | null;
        };
        /** Factor */
        Factor: {
            /** Name */
            name: string;
            /** Contribution */
            contribution: number;
        };
        /** GeneratedFile */
        GeneratedFile: {
            /** Path */
            path: string;
            /** Language */
            language: string;
            /** Purpose */
            purpose: string;
            /** Content */
            content: string;
            /**
             * Mitigates
             * @default []
             */
            mitigates?: string[];
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Child */
            child: string;
            /** Parent */
            parent: string;
            /** Cardinality */
            cardinality: string;
            /** Columns */
            columns: string[];
            /** On Delete */
            on_delete: string;
            /** Decision */
            decision: string;
            /**
             * Self Reference
             * @default false
             */
            self_reference?: boolean;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Columns */
            columns: number;
            /** Kind */
            kind: string;
            /** Collection */
            collection: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Postgres
             * @enum {string}
             */
            postgres: "up" | "down" | "unconfigured";
            /**
             * Mongo
             * @enum {string}
             */
            mongo: "up" | "down" | "unconfigured";
            /**
             * Database
             * @default up
             * @enum {string}
             */
            database?: "up" | "down" | "unconfigured";
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Available */
            available: boolean;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PlacementChange
         * @description A verdict whose status changed between the initial and final pass.
         */
        PlacementChange: {
            /** Node Id */
            node_id: string;
            /** Rule Id */
            rule_id: string;
            /**
             * Initial
             * @enum {string}
             */
            initial: "SAFE" | "CHANGED" | "BROKEN";
            /**
             * Final
             * @enum {string}
             */
            final: "SAFE" | "CHANGED" | "BROKEN";
        };
        /** PlacementDecision */
        PlacementDecision: {
            /** Relationship Id */
            relationship_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "EMBED" | "REFERENCE" | "REF_ARRAY";
            /**
             * Score
             * @default 0
             */
            score?: number;
            /**
             * Top Factors
             * @default []
             */
            top_factors?: components["schemas"]["Factor"][];
            /**
             * Reason
             * @default
             */
            reason?: string;
            /**
             * Overridden
             * @default false
             */
            overridden?: boolean;
            /** Host */
            host?: string | null;
            ai?: components["schemas"]["AIOpinion"] | null;
            /** Agree */
            agree?: boolean | null;
        };
        /** ProbeOutcome */
        ProbeOutcome: {
            /** Verdict Id */
            verdict_id: string;
            /** Rule Id */
            rule_id: string;
            /** Status */
            status: string;
            /** Description */
            description: string;
            /** Postgres */
            postgres: string;
            /** Mongo */
            mongo: string;
            /** Demonstrates */
            demonstrates: boolean;
            /**
             * Tables Differing
             * @default []
             */
            tables_differing?: string[];
            /**
             * Examples
             * @default []
             */
            examples?: components["schemas"]["RowDiff"][];
        };
        /** QueryOutcome */
        QueryOutcome: {
            /** Query Id */
            query_id: string;
            /** Sql */
            sql: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "MATCH" | "MISMATCH" | "ERROR" | "NOT_TRANSLATED" | "SKIPPED";
            /**
             * Pg Rows
             * @default 0
             */
            pg_rows?: number;
            /**
             * Mongo Rows
             * @default 0
             */
            mongo_rows?: number;
            /**
             * Differing
             * @default []
             */
            differing?: components["schemas"]["RowDiff"][];
            /** Hypothesis */
            hypothesis?: string | null;
            /**
             * Explained By
             * @default []
             */
            explained_by?: string[];
            /** Error */
            error?: string | null;
            /** Pg Error */
            pg_error?: string | null;
        };
        /** QueryTranslation */
        QueryTranslation: {
            /** Query Id */
            query_id: string;
            /** Sql */
            sql: string;
            /** Kind */
            kind: string;
            /** Collection */
            collection?: string | null;
            /**
             * Output Columns
             * @default []
             */
            output_columns?: string[];
            /** Error */
            error?: string | null;
            /**
             * Notes
             * @default []
             */
            notes?: string[];
            /**
             * Mongosh
             * @default
             */
            mongosh?: string;
            /**
             * Python
             * @default
             */
            python?: string;
            /** Transaction Id */
            transaction_id?: string | null;
        };
        /** RowDiff */
        RowDiff: {
            /**
             * Side
             * @enum {string}
             */
            side: "postgres" | "mongo" | "both";
            /** Index */
            index?: number | null;
            /** Postgres */
            postgres?: unknown[] | null;
            /** Mongo */
            mongo?: unknown[] | null;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /** Verify */
            verify: boolean;
            /** Schema Sql */
            schema_sql: string;
            /** Queries Sql */
            queries_sql: string;
            /** Seed Sql */
            seed_sql: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /** Seed */
            seed: number;
            /** Overall Verdict */
            overall_verdict: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            } | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            result: components["schemas"]["CompileResponse"] | null;
            verification: components["schemas"]["VerificationReport"] | null;
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** RunRequest */
        RunRequest: {
            /** Schema Sql */
            schema_sql: string;
            /**
             * Queries Sql
             * @default
             */
            queries_sql?: string;
            /**
             * Seed Sql
             * @default
             */
            seed_sql?: string;
            /**
             * @default {
             *       "target_mongo_version": "7.0",
             *       "transactions_available": true,
             *       "preserve_integer_ids": false,
             *       "uuid_as": "binary",
             *       "rows_per_table": 50,
             *       "relationship_overrides": {},
             *       "access_hints": {}
             *     }
             */
            options?: components["schemas"]["CompileOptions"];
            /**
             * Verify
             * @default false
             */
            verify?: boolean;
            /**
             * Seed
             * @default 0
             */
            seed?: number;
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /** Overall Verdict */
            overall_verdict: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            } | null;
            /** Verify */
            verify: boolean;
            /** Duration Ms */
            duration_ms: number | null;
            /** Schema Preview */
            schema_preview: string;
        };
        /** SampleDetail */
        SampleDetail: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /** Schema Sql */
            schema_sql: string;
            /** Queries Sql */
            queries_sql: string;
            options: components["schemas"]["CompileOptions"];
        };
        /** SampleInfo */
        SampleInfo: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description?: string;
        };
        /**
         * SourceSpan
         * @description 1-based line/column range. ``col_end`` is exclusive.
         */
        SourceSpan: {
            /** Line Start */
            line_start: number;
            /** Col Start */
            col_start: number;
            /** Line End */
            line_end: number;
            /** Col End */
            col_end: number;
        };
        /** UntranslatedCheckDTO */
        UntranslatedCheckDTO: {
            /** Table */
            table: string;
            /** Name */
            name: string | null;
            /** Sql */
            sql: string;
            /** Fragment */
            fragment: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verdict */
        Verdict: {
            /** Node Id */
            node_id: string;
            /** Rule Id */
            rule_id: string;
            /** Ir Node Type */
            ir_node_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "SAFE" | "CHANGED" | "BROKEN";
            /** Outcome */
            outcome: string;
            /** Reason */
            reason: string;
            /** Mitigation */
            mitigation?: string | null;
            /** Mongo Feature */
            mongo_feature?: string | null;
            /**
             * Conditions Evaluated
             * @default []
             */
            conditions_evaluated?: components["schemas"]["ConditionTrace"][];
            source_span?: components["schemas"]["SourceSpan"] | null;
        };
        /** VerificationReport */
        VerificationReport: {
            /** Run Id */
            run_id: string;
            /** Seed */
            seed: number;
            /** Rows */
            rows: {
                [key: string]: number;
            };
            /** Migrated */
            migrated: {
                [key: string]: number;
            };
            /** Queries */
            queries: components["schemas"]["QueryOutcome"][];
            /**
             * Probes
             * @default []
             */
            probes?: components["schemas"]["ProbeOutcome"][];
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    compile_endpoint_api_v1_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_api_v1_runs__run_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_api_v1_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleInfo"][];
                };
            };
        };
    };
    get_sample_api_v1_samples__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
}
