// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Collections with $jsonSchema validators (validationLevel strict).

function ensureCollection(name, options) {
  if (db.getCollectionInfos({ name: name }).length === 0) {
    db.createCollection(name, options);
  } else {
    db.runCommand(Object.assign({ collMod: name }, options));
  }
}

// departments: SQL table departments; _id = departments.id
ensureCollection("departments", {
  validator: {
    $and: [
      {
        $jsonSchema: {
          bsonType: "object",
          required: ["name"],
          properties: {
            _id: {bsonType: "int"},
            name: {bsonType: "string"},
            budget: {bsonType: "decimal"},
            courses: {
              bsonType: "array",
              items: {
                bsonType: "object",
                required: ["id", "code", "title", "credits"],
                properties: {
                  id: {bsonType: "int"},
                  code: {bsonType: "string", maxLength: 10},
                  title: {bsonType: "string"},
                  credits: {bsonType: "int", minimum: 1, maximum: 6},
                  prerequisites: {
                    bsonType: "array",
                    items: {
                      bsonType: "object",
                      required: ["requires_id"],
                      properties: {requires_id: {bsonType: "int"}},
                      additionalProperties: false
                    }
                  },
                  sections: {
                    bsonType: "array",
                    items: {
                      bsonType: "object",
                      required: ["id", "term"],
                      properties: {
                        id: {bsonType: "int"},
                        professor_id: {bsonType: "int"},
                        term: {bsonType: "string", maxLength: 6},
                        room: {bsonType: "string"}
                      },
                      additionalProperties: false
                    }
                  }
                },
                additionalProperties: false
              }
            },
            professors: {
              bsonType: "array",
              items: {
                bsonType: "object",
                required: ["id", "name", "email"],
                properties: {
                  id: {bsonType: "int"},
                  name: {bsonType: "string"},
                  email: {bsonType: "string"},
                  office_hours: {
                    bsonType: "array",
                    items: {
                      bsonType: "object",
                      required: ["id", "weekday", "starts", "ends"],
                      properties: {
                        id: {bsonType: "int"},
                        weekday: {bsonType: "int", minimum: 0, maximum: 6},
                        starts: {bsonType: "string"},
                        ends: {bsonType: "string"}
                      },
                      additionalProperties: false
                    }
                  }
                },
                additionalProperties: false
              }
            }
          },
          additionalProperties: false
        }
      },
      {
        $expr: {
          $allElementsTrue: [
            {
              $map: {
                input: {$ifNull: ["$courses", []]},
                as: "e1",
                in: {
                  $allElementsTrue: [
                    {
                      $map: {
                        input: {$ifNull: ["$$e1.prerequisites", []]},
                        as: "e2",
                        in: {
                          $or: [
                            {$lte: ["$$e1.id", null]},
                            {$lte: ["$$e2.requires_id", null]},
                            {$ne: ["$$e1.id", "$$e2.requires_id"]}
                          ]
                        }
                      }
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    ]
  },
  validationLevel: "strict",
  validationAction: "error"
});

// students: SQL table students; _id = students.id
ensureCollection("students", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: ["name", "email", "enrolled_on"],
      properties: {
        _id: {bsonType: "int"},
        name: {bsonType: "string"},
        email: {bsonType: "string"},
        enrolled_on: {bsonType: "date"},
        advisor_id: {bsonType: "int"},
        gpa: {bsonType: "decimal", minimum: 0, maximum: 4},
        enrollments: {
          bsonType: "array",
          items: {
            bsonType: "object",
            required: ["section_id"],
            properties: {
              section_id: {bsonType: "int"},
              grade: {bsonType: "string", enum: ["A", "B", "C", "D", "F"]}
            },
            additionalProperties: false
          }
        }
      },
      additionalProperties: false
    }
  },
  validationLevel: "strict",
  validationAction: "error"
});
