// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Indexes: unique constraints and foreign-key equivalents.

// unique:departments.name: unique
db.getCollection("departments").createIndex({name: 1}, {name: "uq_departments_name", unique: true});

// unique:professors.email: unique; partial because parents without embedded rows have no such field
db.getCollection("departments").createIndex({"professors.email": 1}, {
  name: "uq_departments_professors_email",
  unique: true,
  partialFilterExpression: {"professors.email": {$exists: true}}
});

// unique:students.email: unique
db.getCollection("students").createIndex({email: 1}, {name: "uq_students_email", unique: true});

// unique:courses.code: unique; partial because parents without embedded rows have no such field
db.getCollection("departments").createIndex({"courses.code": 1}, {
  name: "uq_departments_courses_code",
  unique: true,
  partialFilterExpression: {"courses.code": {$exists: true}}
});

// fk:students.advisor_id->professors.id: supports lookups along the foreign key
db.getCollection("students").createIndex({advisor_id: 1}, {name: "idx_students_advisor_id"});

// fk:prerequisites.requires_id->courses.id: supports lookups along the foreign key
db.getCollection("departments").createIndex({"courses.prerequisites.requires_id": 1}, {name: "idx_departments_courses_prerequisites_requires_id"});

// fk:sections.professor_id->professors.id: supports lookups along the foreign key
db.getCollection("departments").createIndex({"courses.sections.professor_id": 1}, {name: "idx_departments_courses_sections_professor_id"});

// fk:enrollments.section_id->sections.id: supports lookups along the foreign key
db.getCollection("students").createIndex({"enrollments.section_id": 1}, {name: "idx_students_enrollments_section_id"});
