// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Translated queries. Output field names match the SQL column aliases.

// q1: SELECT s.name, e.grade FROM students s JOIN enrollments e ON e.student_id = s.id WHERE e.grade = 'A'
// columns: name, grade
const q1 = db.getCollection("students").aggregate([
  {$replaceRoot: {newRoot: {s: "$$ROOT"}}},
  {$unwind: {path: "$s.enrollments", preserveNullAndEmptyArrays: false}},
  {$match: {"s.enrollments.grade": "A"}},
  {
    $project: {_id: 0, name: {$ifNull: ["$s.name", null]}, grade: {$ifNull: ["$s.enrollments.grade", null]}}
  }
]).toArray();

// q2: SELECT d.name, COUNT(*) FROM departments d LEFT JOIN professors p ON p.department_id = d.id GROUP BY d.name
// columns: name, count
const q2 = db.getCollection("departments").aggregate([
  {$replaceRoot: {newRoot: {d: "$$ROOT"}}},
  {$unwind: {path: "$d.professors", preserveNullAndEmptyArrays: true}},
  {$group: {_id: {g0: "$d.name"}, __a0: {$sum: 1}}},
  {$addFields: {name: {$ifNull: ["$_id.g0", null]}, count: {$ifNull: ["$__a0", null]}}},
  {$project: {_id: 0, name: 1, count: 1}}
]).toArray();

// q3: SELECT AVG(gpa) FROM students
// columns: avg
const q3 = db.getCollection("students").aggregate([
  {$replaceRoot: {newRoot: {students: "$$ROOT"}}},
  {$group: {_id: null, __a0: {$avg: "$students.gpa"}}},
  {$addFields: {avg: {$ifNull: ["$__a0", null]}}},
  {$project: {_id: 0, avg: 1}}
]).toArray();

// ---- transaction t1: all-or-nothing across collections
{
  const session = db.getMongo().startSession();
  session.withTransaction(() => {
    const sdb = session.getDatabase(db.getName());
    // q4: INSERT INTO enrollments (student_id, section_id) VALUES (1, 1)
    sdb.getCollection("students").updateOne({_id: 1}, {$push: {enrollments: {section_id: 1}}});
    // q5: UPDATE sections SET room = 'R1' WHERE id = 1
    sdb.getCollection("departments").updateMany({"courses.sections.id": 1, "courses.sections": {$exists: true}}, {$set: {"courses.$[o0].sections.$[el].room": "R1"}}, {arrayFilters: [{"o0.sections": {$exists: true}}, {"el.id": 1}]});
  });
  session.endSession();
}
