"""Emitters: render collections, indexes and queries as mongosh JavaScript or Python (pymongo).

``Emitter`` is the extension point: a Mongoose/TypeScript emitter only has to implement the same
three methods.
"""

from __future__ import annotations

import textwrap
from typing import Protocol

from schemashift.codegen.collections import CollectionSpec
from schemashift.codegen.indexes import IndexSpec
from schemashift.codegen.queries import TranslatedQuery, WriteOp
from schemashift.codegen.values import js_string, to_js, to_py
from schemashift.models.base import FrozenModel


class GeneratedFile(FrozenModel):
    path: str
    language: str  # "javascript" | "python"
    purpose: str  # validators | indexes | queries | migration | helpers
    content: str
    mitigates: tuple[str, ...] = ()  # verdict node ids the file works around


class Header(FrozenModel):
    version: str
    run_id: str
    timestamp: str

    def lines(self) -> list[str]:
        return [
            f"Generated by SchemaShift {self.version}. Do not edit manually.",
            f"Run: {self.run_id}    Generated at: {self.timestamp}",
        ]


def js_header(h: Header) -> str:
    return "\n".join(f"// {line}" for line in h.lines()) + "\n"


def py_header(h: Header) -> str:
    return "\n".join(f"# {line}" for line in h.lines()) + "\n"


class Emitter(Protocol):
    language: str

    def collections(self, specs: list[CollectionSpec], header: Header) -> GeneratedFile: ...

    def indexes(self, specs: list[IndexSpec], header: Header) -> GeneratedFile: ...

    def queries(self, queries: list[TranslatedQuery], header: Header) -> GeneratedFile: ...


def _create_options(spec: CollectionSpec) -> dict[str, object]:
    return {
        "validator": spec.validator,
        "validationLevel": spec.validation_level,
        "validationAction": spec.validation_action,
    }


def _index_options(spec: IndexSpec) -> dict[str, object]:
    options: dict[str, object] = {"name": spec.name}
    if spec.unique:
        options["unique"] = True
    if spec.partial_filter:
        options["partialFilterExpression"] = spec.partial_filter
    return options


def _group_transactions(queries: list[TranslatedQuery]) -> list[list[TranslatedQuery]]:
    """Consecutive queries of one transaction are grouped; others stand alone."""
    groups: list[list[TranslatedQuery]] = []
    for q in queries:
        if groups and q.transaction_id and groups[-1][-1].transaction_id == q.transaction_id:
            groups[-1].append(q)
        else:
            groups.append([q])
    return groups


# =============================================================================== mongosh
class MongoshEmitter:
    language = "javascript"

    def collections(self, specs: list[CollectionSpec], header: Header) -> GeneratedFile:
        out = [
            js_header(header),
            "// Collections with $jsonSchema validators (validationLevel strict).\n",
        ]
        out.append(
            textwrap.dedent(
                """\
                function ensureCollection(name, options) {
                  if (db.getCollectionInfos({ name: name }).length === 0) {
                    db.createCollection(name, options);
                  } else {
                    db.runCommand(Object.assign({ collMod: name }, options));
                  }
                }
                """
            )
        )
        for spec in specs:
            out.append(f"// {spec.name}: SQL table {spec.table}; {spec.id_description}")
            out.append(
                f"ensureCollection({js_string(spec.name)}, {to_js(_create_options(spec))});\n"
            )
        return GeneratedFile(
            path="mongosh/01_collections.js",
            language=self.language,
            purpose="validators",
            content="\n".join(out),
        )

    def indexes(self, specs: list[IndexSpec], header: Header) -> GeneratedFile:
        out = [js_header(header), "// Indexes: unique constraints and foreign-key equivalents.\n"]
        for spec in specs:
            keys = to_js({k: d for k, d in spec.keys})
            note = f"// {spec.origin}" + (f": {spec.comment}" if spec.comment else "")
            out.append(note)
            out.append(
                f"db.getCollection({js_string(spec.collection)}).createIndex("
                f"{keys}, {to_js(_index_options(spec))});\n"
            )
        return GeneratedFile(
            path="mongosh/02_indexes.js",
            language=self.language,
            purpose="indexes",
            content="\n".join(out),
        )

    def queries(self, queries: list[TranslatedQuery], header: Header) -> GeneratedFile:
        out = [
            js_header(header),
            "// Translated queries. Output field names match the SQL column aliases.\n",
        ]
        for group in _group_transactions(queries):
            txn = group[0].transaction_id
            if txn:
                out.append(f"// ---- transaction {txn}: all-or-nothing across collections")
                out.append("{")
                out.append("  const session = db.getMongo().startSession();")
                out.append("  session.withTransaction(() => {")
                out.append("    const sdb = session.getDatabase(db.getName());")
                for q in group:
                    out.append(textwrap.indent(self._query(q, "sdb"), "    "))
                out.append("  });")
                out.append("  session.endSession();")
                out.append("}\n")
            else:
                out.append(self._query(group[0], "db") + "\n")
        return GeneratedFile(
            path="mongosh/03_queries.js",
            language=self.language,
            purpose="queries",
            content="\n".join(out),
        )

    def _query(self, q: TranslatedQuery, dbvar: str) -> str:
        lines = [f"// {q.query_id}: {q.sql}"]
        if q.error:
            lines.append(f"// NOT TRANSLATED: {q.error}")
            return "\n".join(lines)
        lines.extend(f"// note: {n}" for n in q.notes)
        if q.pipeline is not None:
            lines.append(f"// columns: {', '.join(q.output_columns)}")
            lines.append(
                f"const {q.query_id} = {dbvar}.getCollection({js_string(q.collection or '')})"
                f".aggregate({to_js(q.pipeline)}).toArray();"
            )
            return "\n".join(lines)
        for op in q.operations:
            lines.append(self._write(op, dbvar))
        return "\n".join(lines)

    @staticmethod
    def _write(op: WriteOp, dbvar: str) -> str:
        target = f"{dbvar}.getCollection({js_string(op.collection)})"
        if op.op in ("insertOne", "insertMany"):
            docs = op.documents or []
            arg = to_js(docs[0] if op.op == "insertOne" else docs)
            return f"{target}.{op.op}({arg});"
        args = [to_js(op.filter or {})]
        if op.update is not None:
            args.append(to_js(op.update))
        if op.array_filters:
            args.append(to_js({"arrayFilters": op.array_filters}))
        return f"{target}.{op.op}({', '.join(args)});"


# =============================================================================== pymongo
PY_IMPORTS = (
    "from datetime import datetime, timezone\n"
    "import uuid\n\n"
    "from bson import Decimal128\n"
    "from bson.regex import Regex\n"
)


class PymongoEmitter:
    language = "python"

    def collections(self, specs: list[CollectionSpec], header: Header) -> GeneratedFile:
        out = [
            py_header(header),
            '"""Collections with $jsonSchema validators."""\n',
            PY_IMPORTS,
            "",
        ]
        out.append(
            textwrap.dedent(
                '''\
                def ensure_collection(db, name, options):
                    """Create the collection, or update its validator when it already exists."""
                    if name not in db.list_collection_names():
                        db.create_collection(name, **{
                            "validator": options["validator"],
                            "validationLevel": options["validationLevel"],
                            "validationAction": options["validationAction"],
                        })
                    else:
                        db.command("collMod", name, **options)

                '''
            )
        )
        out.append("def create_collections(db):")
        for spec in specs:
            out.append(f"    # {spec.name}: SQL table {spec.table}; {spec.id_description}")
            out.append(
                f"    ensure_collection(db, {spec.name!r}, "
                f"{textwrap.indent(to_py(_create_options(spec), 1), '').lstrip()})"
            )
        if not specs:
            out.append("    pass")
        return GeneratedFile(
            path="python/schema.py",
            language=self.language,
            purpose="validators",
            content="\n".join(out) + "\n",
        )

    def indexes(self, specs: list[IndexSpec], header: Header) -> GeneratedFile:
        out = [
            py_header(header),
            '"""Indexes: unique constraints and foreign-key equivalents."""\n',
            PY_IMPORTS,
            "",
        ]
        out.append("def create_indexes(db):")
        for spec in specs:
            out.append(f"    # {spec.origin}" + (f": {spec.comment}" if spec.comment else ""))
            keys = to_py(list(spec.keys), 1)
            opts = to_py(_index_options(spec), 1)
            out.append(f"    db[{spec.collection!r}].create_index({keys}, **{opts})")
        if not specs:
            out.append("    pass")
        return GeneratedFile(
            path="python/indexes.py",
            language=self.language,
            purpose="indexes",
            content="\n".join(out) + "\n",
        )

    def queries(self, queries: list[TranslatedQuery], header: Header) -> GeneratedFile:
        out = [
            py_header(header),
            '"""Translated queries (each function takes a pymongo Database)."""\n',
            PY_IMPORTS,
            "",
        ]
        for group in _group_transactions(queries):
            txn = group[0].transaction_id
            if txn:
                out.append(f"def txn_{txn}(client, db):")
                out.append(f'    """Transaction {txn}: all-or-nothing across collections."""')
                out.append("    def body(session):")
                for q in group:
                    out.append(textwrap.indent(self._query_body(q, "session"), "        "))
                out.append("    with client.start_session() as session:")
                out.append("        session.with_transaction(body)\n")
            else:
                out.append(self._function(group[0]))
        return GeneratedFile(
            path="python/queries.py",
            language=self.language,
            purpose="queries",
            content="\n".join(out),
        )

    def _function(self, q: TranslatedQuery) -> str:
        head = f"def {q.query_id}(db):\n"
        doc = f'    """{q.sql.replace(chr(34) * 3, chr(39) * 3)}"""\n'
        return head + doc + textwrap.indent(self._query_body(q, None), "    ") + "\n"

    def _query_body(self, q: TranslatedQuery, session: str | None) -> str:
        if q.error:
            return (
                f"# {q.query_id}: NOT TRANSLATED: {q.error}\nraise NotImplementedError({q.error!r})"
            )
        kw = f", session={session}" if session else ""
        lines = [f"# {q.query_id}: {q.sql}"]
        lines.extend(f"# note: {n}" for n in q.notes)
        if q.pipeline is not None:
            lines.append(f"# columns: {', '.join(q.output_columns)}")
            lines.append(
                f"{'result = ' if not session else 'result_' + q.query_id + ' = '}"
                f"list(db[{q.collection!r}].aggregate({to_py(q.pipeline, 1)}{kw}))"
            )
            if not session:
                lines.append("return result")
            return "\n".join(lines)
        for op in q.operations:
            lines.append(self._write(op, session))
        return "\n".join(lines)

    @staticmethod
    def _write(op: WriteOp, session: str | None) -> str:
        kw = f", session={session}" if session else ""
        target = f"db[{op.collection!r}]"
        if op.op == "insertOne":
            return f"{target}.insert_one({to_py((op.documents or [{}])[0], 1)}{kw})"
        if op.op == "insertMany":
            return f"{target}.insert_many({to_py(op.documents or [], 1)}{kw})"
        method = {
            "updateOne": "update_one",
            "updateMany": "update_many",
            "deleteMany": "delete_many",
        }[op.op]
        args = [to_py(op.filter or {}, 1)]
        if op.update is not None:
            args.append(to_py(op.update, 1))
        if op.array_filters:
            args.append(f"array_filters={to_py(op.array_filters, 1)}")
        return f"{target}.{method}({', '.join(args)}{kw})"
