# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z
# Application-level enforcement helpers. MongoDB has no foreign keys, cascades,
# defaults or sequences: these functions re-create the guarantees marked
# CHANGED or BROKEN by the equivalence checker.
# Requires migrate.py next to this file (or schemashift installed).

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from bson import ObjectId

try:
    from schemashift.codegen.runtime_migrate import convert_value, row_to_doc
except ImportError:  # generated deployment: migrate.py sits next to helpers.py
    from migrate import convert_value, row_to_doc  # type: ignore[import-not-found,no-redef]

PLAN = {'options': {'uuid_as': 'binary', 'preserve_integer_ids': False},
 'roots': ['categories', 'customers', 'orders', 'products'],
 'tables': {'customers': {'kind': 'root',
                          'collection': 'customers',
                          'host': None,
                          'path': [],
                          'dropped': [],
                          'host_columns': [],
                          'id_column': 'id',
                          'fields': {'id': '_id',
                                     'email': 'email',
                                     'name': 'name',
                                     'phone': 'phone',
                                     'created_at': 'created_at'},
                          'scalar_column': None,
                          'pk': ['id'],
                          'identity': ['id'],
                          'columns': {'id': {'base': 'INTEGER',
                                             'is_array': False,
                                             'nullable': False},
                                      'email': {'base': 'TEXT',
                                                'is_array': False,
                                                'nullable': False},
                                      'name': {'base': 'TEXT',
                                               'is_array': False,
                                               'nullable': False},
                                      'phone': {'base': 'TEXT',
                                                'is_array': False,
                                                'nullable': True},
                                      'created_at': {'base': 'TIMESTAMPTZ',
                                                     'is_array': False,
                                                     'nullable': False}}},
            'addresses': {'kind': 'array',
                          'collection': 'customers',
                          'host': 'customers',
                          'path': ['addresses'],
                          'dropped': ['customer_id'],
                          'host_columns': ['id'],
                          'id_column': None,
                          'fields': {'id': 'id',
                                     'line1': 'line1',
                                     'city': 'city',
                                     'postal_code': 'postal_code'},
                          'scalar_column': None,
                          'pk': ['id'],
                          'identity': ['id'],
                          'columns': {'id': {'base': 'INTEGER',
                                             'is_array': False,
                                             'nullable': False},
                                      'customer_id': {'base': 'INTEGER',
                                                      'is_array': False,
                                                      'nullable': False},
                                      'line1': {'base': 'TEXT',
                                                'is_array': False,
                                                'nullable': False},
                                      'city': {'base': 'TEXT',
                                               'is_array': False,
                                               'nullable': False},
                                      'postal_code': {'base': 'VARCHAR',
                                                      'is_array': False,
                                                      'nullable': True}}},
            'categories': {'kind': 'root',
                           'collection': 'categories',
                           'host': None,
                           'path': [],
                           'dropped': [],
                           'host_columns': [],
                           'id_column': 'id',
                           'fields': {'id': '_id', 'name': 'name', 'parent_id': 'parent_id'},
                           'scalar_column': None,
                           'pk': ['id'],
                           'identity': ['id'],
                           'columns': {'id': {'base': 'INTEGER',
                                              'is_array': False,
                                              'nullable': False},
                                       'name': {'base': 'TEXT',
                                                'is_array': False,
                                                'nullable': False},
                                       'parent_id': {'base': 'INTEGER',
                                                     'is_array': False,
                                                     'nullable': True}}},
            'products': {'kind': 'root',
                         'collection': 'products',
                         'host': None,
                         'path': [],
                         'dropped': [],
                         'host_columns': [],
                         'id_column': 'id',
                         'fields': {'id': '_id',
                                    'sku': 'sku',
                                    'title': 'title',
                                    'price': 'price',
                                    'stock': 'stock'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'sku': {'base': 'VARCHAR',
                                             'is_array': False,
                                             'nullable': False},
                                     'title': {'base': 'TEXT',
                                               'is_array': False,
                                               'nullable': False},
                                     'price': {'base': 'DECIMAL',
                                               'is_array': False,
                                               'nullable': False},
                                     'stock': {'base': 'INTEGER',
                                               'is_array': False,
                                               'nullable': False}}},
            'product_categories': {'kind': 'ref_scalars',
                                   'collection': 'categories',
                                   'host': 'categories',
                                   'path': ['product_ids'],
                                   'dropped': ['category_id'],
                                   'host_columns': ['id'],
                                   'id_column': None,
                                   'fields': {},
                                   'scalar_column': 'product_id',
                                   'pk': ['product_id', 'category_id'],
                                   'identity': [],
                                   'columns': {'product_id': {'base': 'INTEGER',
                                                              'is_array': False,
                                                              'nullable': False},
                                               'category_id': {'base': 'INTEGER',
                                                               'is_array': False,
                                                               'nullable': False}}},
            'orders': {'kind': 'root',
                       'collection': 'orders',
                       'host': None,
                       'path': [],
                       'dropped': [],
                       'host_columns': [],
                       'id_column': 'id',
                       'fields': {'id': '_id',
                                  'customer_id': 'customer_id',
                                  'status': 'status',
                                  'placed_at': 'placed_at',
                                  'total': 'total'},
                       'scalar_column': None,
                       'pk': ['id'],
                       'identity': ['id'],
                       'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                   'customer_id': {'base': 'INTEGER',
                                                   'is_array': False,
                                                   'nullable': False},
                                   'status': {'base': 'ENUM', 'is_array': False, 'nullable': False},
                                   'placed_at': {'base': 'TIMESTAMPTZ',
                                                 'is_array': False,
                                                 'nullable': False},
                                   'total': {'base': 'DECIMAL',
                                             'is_array': False,
                                             'nullable': False}}},
            'order_items': {'kind': 'array',
                            'collection': 'orders',
                            'host': 'orders',
                            'path': ['order_items'],
                            'dropped': ['order_id'],
                            'host_columns': ['id'],
                            'id_column': None,
                            'fields': {'id': 'id',
                                       'product_id': 'product_id',
                                       'quantity': 'quantity',
                                       'unit_price': 'unit_price'},
                            'scalar_column': None,
                            'pk': ['id'],
                            'identity': ['id'],
                            'columns': {'id': {'base': 'INTEGER',
                                               'is_array': False,
                                               'nullable': False},
                                        'order_id': {'base': 'INTEGER',
                                                     'is_array': False,
                                                     'nullable': False},
                                        'product_id': {'base': 'INTEGER',
                                                       'is_array': False,
                                                       'nullable': False},
                                        'quantity': {'base': 'INTEGER',
                                                     'is_array': False,
                                                     'nullable': False},
                                        'unit_price': {'base': 'DECIMAL',
                                                       'is_array': False,
                                                       'nullable': False}}},
            'payments': {'kind': 'object',
                         'collection': 'orders',
                         'host': 'orders',
                         'path': ['payments'],
                         'dropped': ['order_id'],
                         'host_columns': ['id'],
                         'id_column': None,
                         'fields': {'id': 'id', 'amount': 'amount', 'paid_at': 'paid_at'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'order_id': {'base': 'INTEGER',
                                                  'is_array': False,
                                                  'nullable': False},
                                     'amount': {'base': 'DECIMAL',
                                                'is_array': False,
                                                'nullable': False},
                                     'paid_at': {'base': 'TIMESTAMPTZ',
                                                 'is_array': False,
                                                 'nullable': True}}},
            'reviews': {'kind': 'array',
                        'collection': 'products',
                        'host': 'products',
                        'path': ['reviews'],
                        'dropped': ['product_id'],
                        'host_columns': ['id'],
                        'id_column': None,
                        'fields': {'id': 'id',
                                   'customer_id': 'customer_id',
                                   'stars': 'stars',
                                   'body': 'body'},
                        'scalar_column': None,
                        'pk': ['id'],
                        'identity': ['id'],
                        'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                    'product_id': {'base': 'INTEGER',
                                                   'is_array': False,
                                                   'nullable': False},
                                    'customer_id': {'base': 'INTEGER',
                                                    'is_array': False,
                                                    'nullable': False},
                                    'stars': {'base': 'INTEGER',
                                              'is_array': False,
                                              'nullable': False},
                                    'body': {'base': 'TEXT',
                                             'is_array': False,
                                             'nullable': True}}}},
 'relationships': [{'id': 'fk:addresses.customer_id->customers.id',
                    'child': 'addresses',
                    'parent': 'customers',
                    'columns': ['customer_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:categories.parent_id->categories.id',
                    'child': 'categories',
                    'parent': 'categories',
                    'columns': ['parent_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'SET NULL',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:product_categories.product_id->products.id',
                    'child': 'product_categories',
                    'parent': 'products',
                    'columns': ['product_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:product_categories.category_id->categories.id',
                    'child': 'product_categories',
                    'parent': 'categories',
                    'columns': ['category_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:orders.customer_id->customers.id',
                    'child': 'orders',
                    'parent': 'customers',
                    'columns': ['customer_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'NO ACTION',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:order_items.order_id->orders.id',
                    'child': 'order_items',
                    'parent': 'orders',
                    'columns': ['order_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:order_items.product_id->products.id',
                    'child': 'order_items',
                    'parent': 'products',
                    'columns': ['product_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'NO ACTION',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:payments.order_id->orders.id',
                    'child': 'payments',
                    'parent': 'orders',
                    'columns': ['order_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'NO ACTION',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:reviews.product_id->products.id',
                    'child': 'reviews',
                    'parent': 'products',
                    'columns': ['product_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:reviews.customer_id->customers.id',
                    'child': 'reviews',
                    'parent': 'customers',
                    'columns': ['customer_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False}],
 'defaults': {'customers': {'created_at': {'kind': 'now', 'value': None}},
              'products': {'stock': {'kind': 'literal', 'value': 0}},
              'orders': {'status': {'kind': 'literal', 'value': 'pending'},
                         'placed_at': {'kind': 'now', 'value': None}}},
 'unique': {'customers': [['email'], ['phone']],
            'categories': [['name']],
            'products': [['sku']],
            'order_items': [['order_id', 'product_id']],
            'payments': [['order_id']]}}


# --- Runtime of the generated ... (runtime elided) ...

# ---- per-table helpers (generated) ------------------------------------------

def insert_addresses(db, values, session=None):
    # Mitigates:
    #   auto_increment:addresses.id (CHANGED): EQ-AUTOINC
    #   pk:addresses.id (CHANGED): EQ-ENTITY-UNIQ
    """INSERT INTO addresses: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'addresses', values, session)


def delete_addresses(client, db, **match):
    """DELETE FROM addresses WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'addresses', match, session)
    )


def insert_categories(db, values, session=None):
    # Mitigates:
    #   auto_increment:categories.id (CHANGED): EQ-AUTOINC
    #   fk:categories.parent_id->categories.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO categories: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'categories', values, session)


def delete_categories(client, db, **match):
    # Mitigates:
    #   set_null:categories.parent_id->categories.id (BROKEN): EQ-SET-NULL
    #   cascade_delete:product_categories.category_id->categories.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM categories WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'categories', match, session)
    )


def update_categories(client, db, match, changes):
    """UPDATE categories SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'categories', match, changes, session
        ),
    )


def insert_customers(db, values, session=None):
    # Mitigates:
    #   auto_increment:customers.id (CHANGED): EQ-AUTOINC
    #   default:customers.created_at (CHANGED): EQ-DEFAULT
    #   unique:customers.phone (CHANGED): EQ-VALUE-UNIQ
    """INSERT INTO customers: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'customers', values, session)


def delete_customers(client, db, **match):
    # Mitigates:
    #   restrict_delete:orders.customer_id->customers.id (CHANGED): EQ-RESTRICT
    #   cascade_delete:reviews.customer_id->customers.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM customers WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'customers', match, session)
    )


def update_customers(client, db, match, changes):
    """UPDATE customers SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'customers', match, changes, session
        ),
    )


def insert_order_items(db, values, session=None):
    # Mitigates:
    #   auto_increment:order_items.id (CHANGED): EQ-AUTOINC
    #   pk:order_items.id (CHANGED): EQ-ENTITY-UNIQ
    #   unique:order_items.order_id,product_id (CHANGED): EQ-VALUE-UNIQ
    #   fk:order_items.product_id->products.id (CHANGED): EQ-REF-INTEGRITY
    #   cross_unique:order_items.order_id,product_id (CHANGED): EQ-CROSS-UNIQ
    """INSERT INTO order_items: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'order_items', values, session)


def delete_order_items(client, db, **match):
    """DELETE FROM order_items WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'order_items', match, session)
    )


def insert_orders(db, values, session=None):
    # Mitigates:
    #   auto_increment:orders.id (CHANGED): EQ-AUTOINC
    #   default:orders.status (CHANGED): EQ-DEFAULT
    #   default:orders.placed_at (CHANGED): EQ-DEFAULT
    #   fk:orders.customer_id->customers.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO orders: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'orders', values, session)


def delete_orders(client, db, **match):
    # Mitigates:
    #   restrict_delete:payments.order_id->orders.id (CHANGED): EQ-RESTRICT
    """DELETE FROM orders WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'orders', match, session)
    )


def update_orders(client, db, match, changes):
    """UPDATE orders SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'orders', match, changes, session
        ),
    )


def insert_payments(db, values, session=None):
    # Mitigates:
    #   auto_increment:payments.id (CHANGED): EQ-AUTOINC
    """INSERT INTO payments: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'payments', values, session)


def delete_payments(client, db, **match):
    """DELETE FROM payments WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'payments', match, session)
    )


def insert_product_categories(db, values, session=None):
    # Mitigates:
    #   pk:product_categories.product_id,category_id (CHANGED): EQ-ENTITY-UNIQ
    #   fk:product_categories.product_id->products.id (CHANGED): EQ-REF-INTEGRITY
    #   fk:product_categories.category_id->categories.id (CHANGED): EQ-REF-INTEGRITY
    #   cross_unique:product_categories.product_id,category_id (BROKEN): EQ-CROSS-UNIQ
    """INSERT INTO product_categories: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'product_categories', values, session)


def delete_product_categories(client, db, **match):
    """DELETE FROM product_categories WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'product_categories', match, session)
    )


def insert_products(db, values, session=None):
    # Mitigates:
    #   auto_increment:products.id (CHANGED): EQ-AUTOINC
    #   default:products.stock (CHANGED): EQ-DEFAULT
    """INSERT INTO products: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'products', values, session)


def delete_products(client, db, **match):
    # Mitigates:
    #   cascade_delete:product_categories.product_id->products.id (BROKEN): EQ-CASCADE-DEL
    #   restrict_delete:order_items.product_id->products.id (CHANGED): EQ-RESTRICT
    """DELETE FROM products WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'products', match, session)
    )


def update_products(client, db, match, changes):
    """UPDATE products SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'products', match, changes, session
        ),
    )


def insert_reviews(db, values, session=None):
    # Mitigates:
    #   auto_increment:reviews.id (CHANGED): EQ-AUTOINC
    #   pk:reviews.id (CHANGED): EQ-ENTITY-UNIQ
    #   fk:reviews.customer_id->customers.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO reviews: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'reviews', values, session)


def delete_reviews(client, db, **match):
    """DELETE FROM reviews WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'reviews', match, session)
    )
