# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Indexes: unique constraints and foreign-key equivalents."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def create_indexes(db):
    # unique:customers.email: unique
    db['customers'].create_index([['email', 1]], **{'name': 'uq_customers_email', 'unique': True})
    # unique:customers.phone: unique; partial so that NULLs (absent fields) do not collide
    db['customers'].create_index([['phone', 1]], **{
        'name': 'uq_customers_phone',
        'unique': True,
        'partialFilterExpression': {'phone': {'$exists': True}},
    })
    # unique:categories.name: unique
    db['categories'].create_index([['name', 1]], **{'name': 'uq_categories_name', 'unique': True})
    # unique:products.sku: unique
    db['products'].create_index([['sku', 1]], **{'name': 'uq_products_sku', 'unique': True})
    # fk:categories.parent_id->categories.id: supports lookups along the foreign key
    db['categories'].create_index([['parent_id', 1]], **{'name': 'idx_categories_parent_id'})
    # fk:orders.customer_id->customers.id: supports lookups along the foreign key
    db['orders'].create_index([['customer_id', 1]], **{'name': 'idx_orders_customer_id'})
    # fk:order_items.product_id->products.id: supports lookups along the foreign key
    db['orders'].create_index([['order_items.product_id', 1]], **{'name': 'idx_orders_order_items_product_id'})
    # fk:reviews.customer_id->customers.id: supports lookups along the foreign key
    db['products'].create_index([['reviews.customer_id', 1]], **{'name': 'idx_products_reviews_customer_id'})
    # m2n:product_categories: multikey index for reverse lookups of the reference array
    db['categories'].create_index([['product_ids', 1]], **{'name': 'idx_categories_product_ids'})
