# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Translated queries (each function takes a pymongo Database)."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def q1(db):
    """SELECT c.name, COUNT(*) AS n, SUM(o.total) AS spent FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.name ORDER BY spent DESC LIMIT 10"""
    # q1: SELECT c.name, COUNT(*) AS n, SUM(o.total) AS spent FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.name ORDER BY spent DESC LIMIT 10
    # columns: name, n, spent
    result = list(db['customers'].aggregate([
            {'$replaceRoot': {'newRoot': {'c': '$$ROOT'}}},
            {
                '$lookup': {'from': 'orders', 'localField': 'c._id', 'foreignField': 'customer_id', 'as': 'o'},
            },
            {'$unwind': {'path': '$o', 'preserveNullAndEmptyArrays': False}},
            {
                '$group': {
                    '_id': {'g0': '$c.name'},
                    '__a0': {'$sum': 1},
                    '__a1': {'$sum': '$o.total'},
                    '__a1_n': {'$sum': {'$cond': [{'$gt': ['$o.total', None]}, 1, 0]}},
                },
            },
            {
                '$addFields': {
                    'name': {'$ifNull': ['$_id.g0', None]},
                    'n': {'$ifNull': ['$__a0', None]},
                    'spent': {'$ifNull': [{'$cond': [{'$eq': ['$__a1_n', 0]}, None, '$__a1']}, None]},
                },
            },
            {'$addFields': {'_n0': {'$cond': [{'$lte': ['$spent', None]}, 1, 0]}}},
            {'$sort': {'_n0': -1, 'spent': -1}},
            {'$limit': 10},
            {'$project': {'_id': 0, 'name': 1, 'n': 1, 'spent': 1}},
        ]))
    return result

def q2(db):
    """SELECT p.title, AVG(r.stars) AS avg_stars FROM products p LEFT JOIN reviews r ON r.product_id = p.id GROUP BY p.title"""
    # q2: SELECT p.title, AVG(r.stars) AS avg_stars FROM products p LEFT JOIN reviews r ON r.product_id = p.id GROUP BY p.title
    # columns: title, avg_stars
    result = list(db['products'].aggregate([
            {'$replaceRoot': {'newRoot': {'p': '$$ROOT'}}},
            {'$unwind': {'path': '$p.reviews', 'preserveNullAndEmptyArrays': True}},
            {'$group': {'_id': {'g0': '$p.title'}, '__a0': {'$avg': '$p.reviews.stars'}}},
            {
                '$addFields': {'title': {'$ifNull': ['$_id.g0', None]}, 'avg_stars': {'$ifNull': ['$__a0', None]}},
            },
            {'$project': {'_id': 0, 'title': 1, 'avg_stars': 1}},
        ]))
    return result

def q3(db):
    """SELECT o.id, oi.quantity FROM orders o JOIN order_items oi ON oi.order_id = o.id WHERE o.status = 'paid'"""
    # q3: SELECT o.id, oi.quantity FROM orders o JOIN order_items oi ON oi.order_id = o.id WHERE o.status = 'paid'
    # columns: id, quantity
    result = list(db['orders'].aggregate([
            {'$match': {'status': 'paid'}},
            {'$replaceRoot': {'newRoot': {'o': '$$ROOT'}}},
            {'$unwind': {'path': '$o.order_items', 'preserveNullAndEmptyArrays': False}},
            {
                '$project': {
                    '_id': 0,
                    'id': {'$ifNull': ['$o._id', None]},
                    'quantity': {'$ifNull': ['$o.order_items.quantity', None]},
                },
            },
        ]))
    return result

def txn_t1(client, db):
    """Transaction t1: all-or-nothing across collections."""
    def body(session):
        # q4: INSERT INTO orders (customer_id, total) VALUES (1, 10)
        # note: orders.id is auto-generated: allocated by the insert helper (counter or ObjectId), not by this statement
        db['orders'].insert_one({
                'customer_id': 1,
                'status': 'pending',
                'placed_at': datetime.now(timezone.utc),
                'total': Decimal128('10'),
            }, session=session)
        # q5: UPDATE products SET stock = stock - 1 WHERE id = 1
        db['products'].update_many({'_id': 1}, [{'$set': {'stock': {'$subtract': ['$stock', 1]}}}], session=session)
    with client.start_session() as session:
        session.with_transaction(body)
