# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Collections with $jsonSchema validators."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def ensure_collection(db, name, options):
    """Create the collection, or update its validator when it already exists."""
    if name not in db.list_collection_names():
        db.create_collection(name, **{
            "validator": options["validator"],
            "validationLevel": options["validationLevel"],
            "validationAction": options["validationAction"],
        })
    else:
        db.command("collMod", name, **options)


def create_collections(db):
    # categories: SQL table categories; _id = categories.id
    ensure_collection(db, 'categories', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['name'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'name': {'bsonType': 'string'},
                    'parent_id': {'bsonType': 'int'},
                    'product_ids': {'bsonType': 'array', 'items': {'bsonType': 'int'}, 'uniqueItems': True},
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # customers: SQL table customers; _id = customers.id
    ensure_collection(db, 'customers', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['email', 'name', 'created_at'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'email': {'bsonType': 'string'},
                    'name': {'bsonType': 'string'},
                    'phone': {'bsonType': 'string'},
                    'created_at': {'bsonType': 'date'},
                    'addresses': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['id', 'line1', 'city'],
                            'properties': {
                                'id': {'bsonType': 'int'},
                                'line1': {'bsonType': 'string'},
                                'city': {'bsonType': 'string'},
                                'postal_code': {'bsonType': 'string', 'maxLength': 10},
                            },
                            'additionalProperties': False,
                        },
                    },
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # orders: SQL table orders; _id = orders.id
    ensure_collection(db, 'orders', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['customer_id', 'status', 'placed_at', 'total'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'customer_id': {'bsonType': 'int'},
                    'status': {'bsonType': 'string', 'enum': ['pending', 'paid', 'shipped', 'cancelled']},
                    'placed_at': {'bsonType': 'date'},
                    'total': {'bsonType': 'decimal'},
                    'order_items': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['id', 'product_id', 'quantity', 'unit_price'],
                            'properties': {
                                'id': {'bsonType': 'int'},
                                'product_id': {'bsonType': 'int'},
                                'quantity': {'bsonType': 'int', 'minimum': 0, 'exclusiveMinimum': True},
                                'unit_price': {'bsonType': 'decimal'},
                            },
                            'additionalProperties': False,
                        },
                    },
                    'payments': {
                        'bsonType': 'object',
                        'required': ['id', 'amount'],
                        'properties': {
                            'id': {'bsonType': 'int'},
                            'amount': {'bsonType': 'decimal'},
                            'paid_at': {'bsonType': 'date'},
                        },
                        'additionalProperties': False,
                    },
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # products: SQL table products; _id = products.id
    ensure_collection(db, 'products', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['sku', 'title', 'price', 'stock'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'sku': {'bsonType': 'string', 'maxLength': 20},
                    'title': {'bsonType': 'string'},
                    'price': {'bsonType': 'decimal', 'minimum': 0},
                    'stock': {'bsonType': 'int', 'minimum': 0},
                    'reviews': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['id', 'customer_id', 'stars'],
                            'properties': {
                                'id': {'bsonType': 'int'},
                                'customer_id': {'bsonType': 'int'},
                                'stars': {'bsonType': 'int', 'minimum': 1, 'maximum': 5},
                                'body': {'bsonType': 'string'},
                            },
                            'additionalProperties': False,
                        },
                    },
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
