// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Collections with $jsonSchema validators (validationLevel strict).

function ensureCollection(name, options) {
  if (db.getCollectionInfos({ name: name }).length === 0) {
    db.createCollection(name, options);
  } else {
    db.runCommand(Object.assign({ collMod: name }, options));
  }
}

// categories: SQL table categories; _id = categories.id
ensureCollection("categories", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: ["name"],
      properties: {
        _id: {bsonType: "int"},
        name: {bsonType: "string"},
        parent_id: {bsonType: "int"},
        product_ids: {bsonType: "array", items: {bsonType: "int"}, uniqueItems: true}
      },
      additionalProperties: false
    }
  },
  validationLevel: "strict",
  validationAction: "error"
});

// customers: SQL table customers; _id = customers.id
ensureCollection("customers", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: ["email", "name", "created_at"],
      properties: {
        _id: {bsonType: "int"},
        email: {bsonType: "string"},
        name: {bsonType: "string"},
        phone: {bsonType: "string"},
        created_at: {bsonType: "date"},
        addresses: {
          bsonType: "array",
          items: {
            bsonType: "object",
            required: ["id", "line1", "city"],
            properties: {
              id: {bsonType: "int"},
              line1: {bsonType: "string"},
              city: {bsonType: "string"},
              postal_code: {bsonType: "string", maxLength: 10}
            },
            additionalProperties: false
          }
        }
      },
      additionalProperties: false
    }
  },
  validationLevel: "strict",
  validationAction: "error"
});

// orders: SQL table orders; _id = orders.id
ensureCollection("orders", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: ["customer_id", "status", "placed_at", "total"],
      properties: {
        _id: {bsonType: "int"},
        customer_id: {bsonType: "int"},
        status: {bsonType: "string", enum: ["pending", "paid", "shipped", "cancelled"]},
        placed_at: {bsonType: "date"},
        total: {bsonType: "decimal"},
        order_items: {
          bsonType: "array",
          items: {
            bsonType: "object",
            required: ["id", "product_id", "quantity", "unit_price"],
            properties: {
              id: {bsonType: "int"},
              product_id: {bsonType: "int"},
              quantity: {bsonType: "int", minimum: 0, exclusiveMinimum: true},
              unit_price: {bsonType: "decimal"}
            },
            additionalProperties: false
          }
        },
        payments: {
          bsonType: "object",
          required: ["id", "amount"],
          properties: {id: {bsonType: "int"}, amount: {bsonType: "decimal"}, paid_at: {bsonType: "date"}},
          additionalProperties: false
        }
      },
      additionalProperties: false
    }
  },
  validationLevel: "strict",
  validationAction: "error"
});

// products: SQL table products; _id = products.id
ensureCollection("products", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: ["sku", "title", "price", "stock"],
      properties: {
        _id: {bsonType: "int"},
        sku: {bsonType: "string", maxLength: 20},
        title: {bsonType: "string"},
        price: {bsonType: "decimal", minimum: 0},
        stock: {bsonType: "int", minimum: 0},
        reviews: {
          bsonType: "array",
          items: {
            bsonType: "object",
            required: ["id", "customer_id", "stars"],
            properties: {
              id: {bsonType: "int"},
              customer_id: {bsonType: "int"},
              stars: {bsonType: "int", minimum: 1, maximum: 5},
              body: {bsonType: "string"}
            },
            additionalProperties: false
          }
        }
      },
      additionalProperties: false
    }
  },
  validationLevel: "strict",
  validationAction: "error"
});
