// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Indexes: unique constraints and foreign-key equivalents.

// unique:customers.email: unique
db.getCollection("customers").createIndex({email: 1}, {name: "uq_customers_email", unique: true});

// unique:customers.phone: unique; partial so that NULLs (absent fields) do not collide
db.getCollection("customers").createIndex({phone: 1}, {name: "uq_customers_phone", unique: true, partialFilterExpression: {phone: {$exists: true}}});

// unique:categories.name: unique
db.getCollection("categories").createIndex({name: 1}, {name: "uq_categories_name", unique: true});

// unique:products.sku: unique
db.getCollection("products").createIndex({sku: 1}, {name: "uq_products_sku", unique: true});

// fk:categories.parent_id->categories.id: supports lookups along the foreign key
db.getCollection("categories").createIndex({parent_id: 1}, {name: "idx_categories_parent_id"});

// fk:orders.customer_id->customers.id: supports lookups along the foreign key
db.getCollection("orders").createIndex({customer_id: 1}, {name: "idx_orders_customer_id"});

// fk:order_items.product_id->products.id: supports lookups along the foreign key
db.getCollection("orders").createIndex({"order_items.product_id": 1}, {name: "idx_orders_order_items_product_id"});

// fk:reviews.customer_id->customers.id: supports lookups along the foreign key
db.getCollection("products").createIndex({"reviews.customer_id": 1}, {name: "idx_products_reviews_customer_id"});

// m2n:product_categories: multikey index for reverse lookups of the reference array
db.getCollection("categories").createIndex({product_ids: 1}, {name: "idx_categories_product_ids"});
