// Generated by SchemaShift 0.1.0. Do not edit manually.
// Run: snapshot    Generated at: 2026-01-01T00:00:00Z

// Translated queries. Output field names match the SQL column aliases.

// q1: SELECT c.name, COUNT(*) AS n, SUM(o.total) AS spent FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.name ORDER BY spent DESC LIMIT 10
// columns: name, n, spent
const q1 = db.getCollection("customers").aggregate([
  {$replaceRoot: {newRoot: {c: "$$ROOT"}}},
  {$lookup: {from: "orders", localField: "c._id", foreignField: "customer_id", as: "o"}},
  {$unwind: {path: "$o", preserveNullAndEmptyArrays: false}},
  {
    $group: {
      _id: {g0: "$c.name"},
      __a0: {$sum: 1},
      __a1: {$sum: "$o.total"},
      __a1_n: {$sum: {$cond: [{$gt: ["$o.total", null]}, 1, 0]}}
    }
  },
  {
    $addFields: {
      name: {$ifNull: ["$_id.g0", null]},
      n: {$ifNull: ["$__a0", null]},
      spent: {$ifNull: [{$cond: [{$eq: ["$__a1_n", 0]}, null, "$__a1"]}, null]}
    }
  },
  {$addFields: {_n0: {$cond: [{$lte: ["$spent", null]}, 1, 0]}}},
  {$sort: {_n0: -1, spent: -1}},
  {$limit: 10},
  {$project: {_id: 0, name: 1, n: 1, spent: 1}}
]).toArray();

// q2: SELECT p.title, AVG(r.stars) AS avg_stars FROM products p LEFT JOIN reviews r ON r.product_id = p.id GROUP BY p.title
// columns: title, avg_stars
const q2 = db.getCollection("products").aggregate([
  {$replaceRoot: {newRoot: {p: "$$ROOT"}}},
  {$unwind: {path: "$p.reviews", preserveNullAndEmptyArrays: true}},
  {$group: {_id: {g0: "$p.title"}, __a0: {$avg: "$p.reviews.stars"}}},
  {$addFields: {title: {$ifNull: ["$_id.g0", null]}, avg_stars: {$ifNull: ["$__a0", null]}}},
  {$project: {_id: 0, title: 1, avg_stars: 1}}
]).toArray();

// q3: SELECT o.id, oi.quantity FROM orders o JOIN order_items oi ON oi.order_id = o.id WHERE o.status = 'paid'
// columns: id, quantity
const q3 = db.getCollection("orders").aggregate([
  {$match: {status: "paid"}},
  {$replaceRoot: {newRoot: {o: "$$ROOT"}}},
  {$unwind: {path: "$o.order_items", preserveNullAndEmptyArrays: false}},
  {
    $project: {
      _id: 0,
      id: {$ifNull: ["$o._id", null]},
      quantity: {$ifNull: ["$o.order_items.quantity", null]}
    }
  }
]).toArray();

// ---- transaction t1: all-or-nothing across collections
{
  const session = db.getMongo().startSession();
  session.withTransaction(() => {
    const sdb = session.getDatabase(db.getName());
    // q4: INSERT INTO orders (customer_id, total) VALUES (1, 10)
    // note: orders.id is auto-generated: allocated by the insert helper (counter or ObjectId), not by this statement
    sdb.getCollection("orders").insertOne({customer_id: 1, status: "pending", placed_at: new Date(), total: NumberDecimal("10")});
    // q5: UPDATE products SET stock = stock - 1 WHERE id = 1
    sdb.getCollection("products").updateMany({_id: 1}, [{$set: {stock: {$subtract: ["$stock", 1]}}}]);
  });
  session.endSession();
}
