"""Generates docs/RULES.md from the rule registry.

Usage: ``python -m schemashift.equivalence.rules_doc`` writes the file;
``--check`` exits non-zero when the committed file is stale (used in CI).
"""

from __future__ import annotations

import sys
from pathlib import Path

import schemashift.equivalence.rules  # noqa: F401
from schemashift.equivalence.registry import all_rules
from schemashift.equivalence.typemap import TYPE_MAP

DOC_PATH = Path(__file__).resolve().parents[3] / "docs" / "RULES.md"


def render() -> str:
    lines = [
        "# Equivalence rules (MongoDB target)",
        "",
        "<!-- Generated by `python -m schemashift.equivalence.rules_doc`. Do not edit. -->",
        "",
        "Each rule maps one IR node type to a verdict: **SAFE** (guarantee preserved),",
        "**CHANGED** (preserved with a different mechanism or weaker semantics) or",
        "**BROKEN** (MongoDB cannot preserve it without application code).",
        "Reason and mitigation text are templates; `{...}` marks values filled from the node.",
        "",
        "| Rule | IR node | Outcomes |",
        "|---|---|---|",
    ]
    for spec in all_rules():
        outs = ", ".join(f"{o.key}={o.status}" for o in spec.outcomes)
        lines.append(f"| `{spec.rule_id}` | `{spec.node_type.__name__}` | {outs} |")
    lines.append("")
    for spec in all_rules():
        lines.append(f"## {spec.rule_id}: {spec.title}")
        lines.append("")
        lines.append(f"IR node: `{spec.node_type.__name__}`")
        lines.append("")
        for o in spec.outcomes:
            lines.append(f"### {spec.rule_id} / {o.key} -> {o.status}")
            lines.append("")
            lines.append(f"- **Condition:** {o.when}")
            lines.append(f"- **Reason:** {o.reason}")
            if o.mitigation:
                lines.append(f"- **Mitigation:** {o.mitigation}")
            if o.mongo_feature:
                lines.append(f"- **MongoDB feature:** {o.mongo_feature}")
            lines.append("")
    lines.append("## Type map")
    lines.append("")
    lines.append("| PostgreSQL | BSON | Lossy | Note |")
    lines.append("|---|---|---|---|")
    for base, m in TYPE_MAP.items():
        lines.append(f"| {base} | {m.bson} | {'yes' if m.lossy else 'no'} | {m.note} |")
    lines.append("")
    lines.append(
        "NUMERIC/DECIMAL is additionally lossy whenever its scale is greater than 0. "
        "Arrays use the element type's verdict."
    )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else ""
        if current != text:
            sys.stderr.write(
                "docs/RULES.md is stale; run: python -m schemashift.equivalence.rules_doc\n"
            )
            return 1
        return 0
    DOC_PATH.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
