"""Snapshot tests of the generated output for all sample schemas.

Regenerate with ``UPDATE_GOLDEN=1 pytest tests/unit/codegen/test_snapshots.py``.
The shared runtime embedded in migrate.py / helpers.py is elided (it is tested directly).
"""

import os
from pathlib import Path

import pytest

from tests.unit.codegen.helpers import SAMPLE_NAMES, generate_sample

GOLDEN = Path(__file__).parent / "golden"
RUNTIME_MARKER = "# --- Runtime of the generated"
WRAPPER_MARKER = "# ---- per-table helpers (generated)"


def view(path: str, content: str) -> str:
    if RUNTIME_MARKER not in content:
        return content
    head, rest = content.split(RUNTIME_MARKER, 1)
    tail = rest[rest.index(WRAPPER_MARKER) :] if WRAPPER_MARKER in rest else ""
    return f"{head}{RUNTIME_MARKER} ... (runtime elided) ...\n\n{tail}"


@pytest.mark.parametrize("name", SAMPLE_NAMES)
def test_generated_files_match_snapshots(name: str) -> None:
    _, out = generate_sample(name)
    assert {f.path for f in out.files} == {
        "mongosh/01_collections.js",
        "mongosh/02_indexes.js",
        "mongosh/03_queries.js",
        "python/schema.py",
        "python/indexes.py",
        "python/queries.py",
        "python/migrate.py",
        "python/helpers.py",
    }
    for f in out.files:
        target = GOLDEN / name / f.path
        text = view(f.path, f.content)
        if os.environ.get("UPDATE_GOLDEN"):
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8", newline="\n")
        assert target.exists(), f"missing snapshot {target}"
        assert target.read_text(encoding="utf-8") == text, f"{name}/{f.path} changed"


@pytest.mark.parametrize("name", SAMPLE_NAMES)
def test_every_sample_query_translates(name: str) -> None:
    result, out = generate_sample(name)
    assert out.warnings == ()
    assert len(out.queries) == len(result.queries) + sum(
        len(getattr(q, "statements", ())) - 1 for q in result.queries if hasattr(q, "statements")
    )


@pytest.mark.parametrize("name", SAMPLE_NAMES)
def test_generated_python_is_valid_and_headed(name: str) -> None:
    _, out = generate_sample(name)
    for f in out.files:
        assert "Generated by SchemaShift" in f.content and "Do not edit manually" in f.content
        assert "Run: snapshot" in f.content and "2026-01-01T00:00:00Z" in f.content
        if f.language == "python":
            compile(f.content, f.path, "exec")


@pytest.mark.parametrize("name", SAMPLE_NAMES)
def test_untranslatable_checks_get_stub_helpers(name: str) -> None:
    _, out = generate_sample(name)
    assert out.untranslated_checks == ()  # the samples only use translatable CHECKs
