import pytest

from schemashift.codegen import MongoshEmitter, PymongoEmitter, generate_code
from schemashift.codegen.emit import Header
from schemashift.codegen.helpers import helper_plan, ident
from schemashift.codegen.layout import build_layouts
from schemashift.codegen.migration import migration_plan
from schemashift.pipeline import CompileOptions, compile_sql
from tests.unit.codegen.helpers import generate_sample

SQL = """
CREATE TABLE customers (id SERIAL PRIMARY KEY, name TEXT NOT NULL, created TIMESTAMPTZ DEFAULT now());
CREATE TABLE orders (
  id INT PRIMARY KEY, customer_id INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'new', note TEXT, CONSTRAINT ck CHECK (upper(status) = status)
);
"""
QUERIES = """
SELECT c.name, COUNT(*) AS n FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.name;
BEGIN;
INSERT INTO customers (id, name) VALUES (1, 'a');
INSERT INTO orders (id, customer_id) VALUES (1, 1);
COMMIT;
SELECT * FROM ghosts;
"""


REFERENCED = CompileOptions(
    relationship_overrides={"fk:orders.customer_id->customers.id": "REFERENCE"}
)


@pytest.fixture(scope="module")
def generated():  # type: ignore[no-untyped-def]
    options = REFERENCED
    result = compile_sql(SQL, QUERIES, "", options)
    return result, generate_code(result, options, run_id="r1", timestamp="2026-01-01T00:00:00Z")


def test_all_files_are_produced(generated) -> None:  # type: ignore[no-untyped-def]
    _, out = generated
    assert [f.purpose for f in out.files] == [
        "validators",
        "indexes",
        "queries",
        "validators",
        "indexes",
        "queries",
        "migration",
        "helpers",
    ]
    assert {f.language for f in out.files} == {"javascript", "python"}


def test_mongosh_collections_use_an_idempotent_helper(generated) -> None:  # type: ignore[no-untyped-def]
    js = generated[1].file("mongosh/01_collections.js").content
    assert "function ensureCollection" in js and "collMod" in js
    assert 'ensureCollection("customers"' in js and "validationLevel" in js


def test_mongosh_queries_wrap_transactions_and_report_failures(generated) -> None:  # type: ignore[no-untyped-def]
    js = generated[1].file("mongosh/03_queries.js").content
    assert "session.withTransaction" in js and "sdb.getCollection" in js
    assert "NOT TRANSLATED: unknown table 'ghosts'" in js
    assert "const q1 = db.getCollection" in js and "// columns: name, n" in js


def test_python_queries_wrap_transactions_and_raise_for_untranslated(generated) -> None:  # type: ignore[no-untyped-def]
    py = generated[1].file("python/queries.py").content
    assert "def q1(db):" in py and "def txn_t1(client, db):" in py and "with_transaction" in py
    assert "raise NotImplementedError" in py
    compile(py, "queries.py", "exec")


def test_untranslatable_check_gets_a_stub_helper(generated) -> None:  # type: ignore[no-untyped-def]
    result, out = generated
    assert [c.name for c in out.untranslated_checks] == ["ck"]
    helpers = out.file("python/helpers.py").content
    assert "def check_orders_ck(doc):" in helpers and "NotImplementedError" in helpers


def test_helpers_are_annotated_with_the_verdicts_they_mitigate(generated) -> None:  # type: ignore[no-untyped-def]
    _, out = generated
    helpers = out.file("python/helpers.py")
    assert "# Mitigates:" in helpers.content
    assert "cascade_delete:orders.customer_id->customers.id" in helpers.content
    assert "def delete_customers(client, db, **match):" in helpers.content
    assert "default:customers.created" in helpers.content
    assert "cascade_delete:orders.customer_id->customers.id" in helpers.mitigates


def test_migration_script_embeds_plan_and_runtime(generated) -> None:  # type: ignore[no-untyped-def]
    mig = generated[1].file("python/migrate.py").content
    assert mig.index("PLAN = ") < mig.index("def migrate(")
    assert "Usage: python migrate.py" in mig and "def build_documents" in mig
    assert mig.splitlines()[0].startswith("# Generated by SchemaShift")


def test_header_lines() -> None:
    h = Header(version="1.2.3", run_id="abc", timestamp="2026-02-03T04:05:06Z")
    assert h.lines() == [
        "Generated by SchemaShift 1.2.3. Do not edit manually.",
        "Run: abc    Generated at: 2026-02-03T04:05:06Z",
    ]


def test_emitters_can_be_selected() -> None:
    result = compile_sql(SQL, QUERIES)
    only_js = generate_code(result, emitters=(MongoshEmitter(),), run_id="x", timestamp="t")
    assert {f.language for f in only_js.files} == {
        "javascript",
        "python",
    }  # migration + helpers always
    assert sum(f.language == "javascript" for f in only_js.files) == 3
    only_py = generate_code(result, emitters=(PymongoEmitter(),), run_id="x", timestamp="t")
    assert not any(f.language == "javascript" for f in only_py.files)


def test_default_timestamp_is_current() -> None:
    out = generate_code(compile_sql(SQL))
    assert "Generated at: 20" in out.files[0].content


def test_file_lookup_missing() -> None:
    with pytest.raises(KeyError):
        generate_code(compile_sql(SQL)).file("nope")


def test_migration_plan_describes_every_table() -> None:
    result = compile_sql(SQL)
    plan = migration_plan(
        result.schema_, build_layouts(result.graph, result.plan), CompileOptions()
    )
    assert set(plan["tables"]) == {"customers", "orders"}
    assert plan["tables"]["customers"]["identity"] == ["id"]
    assert plan["tables"]["orders"]["columns"]["note"]["nullable"] is True
    assert plan["roots"] == sorted(n for n, t in plan["tables"].items() if t["kind"] == "root")


def test_helper_plan_has_relationships_defaults_and_unique_keys() -> None:
    result = compile_sql(
        SQL
        + "CREATE TABLE u (id INT PRIMARY KEY, e TEXT UNIQUE, d TIMESTAMP DEFAULT '2024-01-01');",
        options=REFERENCED,
    )
    plan = helper_plan(result, build_layouts(result.graph, result.plan), REFERENCED)
    rel = plan["relationships"][0]
    assert (rel["child"], rel["parent"], rel["on_delete"], rel["embedded"]) == (
        "orders",
        "customers",
        "CASCADE",
        False,
    )
    assert plan["defaults"]["orders"]["status"] == {"kind": "literal", "value": "new"}
    assert plan["defaults"]["customers"]["created"]["kind"] == "now"
    assert plan["unique"]["u"] == [["e"]]


def test_ident_sanitises_names() -> None:
    assert ident("Order Items") == "order_items" and ident("!!") == "t"


@pytest.mark.parametrize("name", ["blog", "banking"])
def test_sample_helpers_wrap_every_table(name: str) -> None:
    result, out = generate_sample(name)
    text = out.file("python/helpers.py").content
    for table in result.schema_.tables:
        assert f"def insert_{ident(table)}(db, values, session=None):" in text
        assert f"def delete_{ident(table)}(client, db, **match):" in text


def test_generated_files_embed_the_runtime_sources_verbatim(generated) -> None:  # type: ignore[no-untyped-def]
    from schemashift.codegen.helpers import MARKER
    from schemashift.codegen.helpers import RUNTIME as HELPERS_RUNTIME
    from schemashift.codegen.migration import RUNTIME as MIGRATION_RUNTIME

    _, out = generated
    for generated_path, runtime_path in (
        ("python/migrate.py", MIGRATION_RUNTIME),
        ("python/helpers.py", HELPERS_RUNTIME),
    ):
        source = runtime_path.read_text(encoding="utf-8")
        body = source[source.index(MARKER) :]
        assert body in out.file(generated_path).content
