CREATE TABLE customers (id INT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE orders (
  id INT PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  total NUMERIC(10,2) NOT NULL DEFAULT 0
);
