CREATE TABLE p (id INT PRIMARY KEY);
CREATE TABLE c1 (id INT PRIMARY KEY, p_id INT REFERENCES p(id) ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE c2 (id INT PRIMARY KEY, p_id INT REFERENCES p(id) ON DELETE NO ACTION ON UPDATE RESTRICT);
CREATE TABLE c3 (id INT PRIMARY KEY, p_id INT DEFAULT 1 REFERENCES p(id) ON DELETE SET DEFAULT ON UPDATE SET NULL);
CREATE TABLE c4 (id INT PRIMARY KEY, p_id INT REFERENCES p);
