CREATE TABLE a (x INT, y INT, PRIMARY KEY (x, y));
CREATE TABLE b (
  id INT PRIMARY KEY,
  ax INT, ay INT,
  CONSTRAINT fk_b_a FOREIGN KEY (ax, ay) REFERENCES a (x, y) ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT uq_b UNIQUE (ax, ay)
);
