CREATE TABLE ok1 (id INT PRIMARY KEY);
CREATE TABLE broken (id INT,, );
CREATE TRIGGER trg BEFORE INSERT ON ok1 FOR EACH ROW EXECUTE FUNCTION f();
CREATE TABLE ok2 (id INT PRIMARY KEY, ok1_id INT REFERENCES ok1(id));
