# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z
# Application-level enforcement helpers. MongoDB has no foreign keys, cascades,
# defaults or sequences: these functions re-create the guarantees marked
# CHANGED or BROKEN by the equivalence checker.
# Requires migrate.py next to this file (or schemashift installed).

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from bson import ObjectId

try:
    from schemashift.codegen.runtime_migrate import convert_value, row_to_doc
except ImportError:  # generated deployment: migrate.py sits next to helpers.py
    from migrate import convert_value, row_to_doc  # type: ignore[import-not-found,no-redef]

PLAN = {'options': {'uuid_as': 'binary', 'preserve_integer_ids': False},
 'roots': ['accounts', 'branches', 'customers', 'transactions'],
 'tables': {'branches': {'kind': 'root',
                         'collection': 'branches',
                         'host': None,
                         'path': [],
                         'dropped': [],
                         'host_columns': [],
                         'id_column': 'id',
                         'fields': {'id': '_id', 'name': 'name', 'city': 'city'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'name': {'base': 'TEXT', 'is_array': False, 'nullable': False},
                                     'city': {'base': 'TEXT',
                                              'is_array': False,
                                              'nullable': False}}},
            'customers': {'kind': 'root',
                          'collection': 'customers',
                          'host': None,
                          'path': [],
                          'dropped': [],
                          'host_columns': [],
                          'id_column': 'id',
                          'fields': {'id': '_id',
                                     'full_name': 'full_name',
                                     'email': 'email',
                                     'phone': 'phone',
                                     'home_branch_id': 'home_branch_id',
                                     'created_at': 'created_at'},
                          'scalar_column': None,
                          'pk': ['id'],
                          'identity': ['id'],
                          'columns': {'id': {'base': 'INTEGER',
                                             'is_array': False,
                                             'nullable': False},
                                      'full_name': {'base': 'TEXT',
                                                    'is_array': False,
                                                    'nullable': False},
                                      'email': {'base': 'TEXT',
                                                'is_array': False,
                                                'nullable': False},
                                      'phone': {'base': 'TEXT',
                                                'is_array': False,
                                                'nullable': True},
                                      'home_branch_id': {'base': 'INTEGER',
                                                         'is_array': False,
                                                         'nullable': True},
                                      'created_at': {'base': 'TIMESTAMPTZ',
                                                     'is_array': False,
                                                     'nullable': False}}},
            'kyc_profiles': {'kind': 'object',
                             'collection': 'customers',
                             'host': 'customers',
                             'path': ['kyc_profiles'],
                             'dropped': ['customer_id'],
                             'host_columns': ['id'],
                             'id_column': None,
                             'fields': {'national_id': 'national_id',
                                        'verified': 'verified',
                                        'verified_at': 'verified_at'},
                             'scalar_column': None,
                             'pk': ['customer_id'],
                             'identity': [],
                             'columns': {'customer_id': {'base': 'INTEGER',
                                                         'is_array': False,
                                                         'nullable': False},
                                         'national_id': {'base': 'TEXT',
                                                         'is_array': False,
                                                         'nullable': False},
                                         'verified': {'base': 'BOOLEAN',
                                                      'is_array': False,
                                                      'nullable': False},
                                         'verified_at': {'base': 'TIMESTAMPTZ',
                                                         'is_array': False,
                                                         'nullable': True}}},
            'accounts': {'kind': 'root',
                         'collection': 'accounts',
                         'host': None,
                         'path': [],
                         'dropped': [],
                         'host_columns': [],
                         'id_column': 'id',
                         'fields': {'id': '_id',
                                    'customer_id': 'customer_id',
                                    'branch_id': 'branch_id',
                                    'kind': 'kind',
                                    'balance': 'balance',
                                    'opened_at': 'opened_at'},
                         'scalar_column': None,
                         'pk': ['id'],
                         'identity': ['id'],
                         'columns': {'id': {'base': 'INTEGER',
                                            'is_array': False,
                                            'nullable': False},
                                     'customer_id': {'base': 'INTEGER',
                                                     'is_array': False,
                                                     'nullable': False},
                                     'branch_id': {'base': 'INTEGER',
                                                   'is_array': False,
                                                   'nullable': False},
                                     'kind': {'base': 'ENUM', 'is_array': False, 'nullable': False},
                                     'balance': {'base': 'DECIMAL',
                                                 'is_array': False,
                                                 'nullable': False},
                                     'opened_at': {'base': 'TIMESTAMPTZ',
                                                   'is_array': False,
                                                   'nullable': False}}},
            'transactions': {'kind': 'root',
                             'collection': 'transactions',
                             'host': None,
                             'path': [],
                             'dropped': [],
                             'host_columns': [],
                             'id_column': 'id',
                             'fields': {'id': '_id',
                                        'account_id': 'account_id',
                                        'kind': 'kind',
                                        'amount': 'amount',
                                        'created_at': 'created_at',
                                        'memo': 'memo'},
                             'scalar_column': None,
                             'pk': ['id'],
                             'identity': ['id'],
                             'columns': {'id': {'base': 'BIGINT',
                                                'is_array': False,
                                                'nullable': False},
                                         'account_id': {'base': 'INTEGER',
                                                        'is_array': False,
                                                        'nullable': False},
                                         'kind': {'base': 'ENUM',
                                                  'is_array': False,
                                                  'nullable': False},
                                         'amount': {'base': 'DECIMAL',
                                                    'is_array': False,
                                                    'nullable': False},
                                         'created_at': {'base': 'TIMESTAMPTZ',
                                                        'is_array': False,
                                                        'nullable': False},
                                         'memo': {'base': 'TEXT',
                                                  'is_array': False,
                                                  'nullable': True}}},
            'cards': {'kind': 'array',
                      'collection': 'accounts',
                      'host': 'accounts',
                      'path': ['cards'],
                      'dropped': ['account_id'],
                      'host_columns': ['id'],
                      'id_column': None,
                      'fields': {'id': 'id', 'number': 'number', 'expires': 'expires'},
                      'scalar_column': None,
                      'pk': ['id'],
                      'identity': ['id'],
                      'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                  'account_id': {'base': 'INTEGER',
                                                 'is_array': False,
                                                 'nullable': False},
                                  'number': {'base': 'CHAR', 'is_array': False, 'nullable': False},
                                  'expires': {'base': 'DATE',
                                              'is_array': False,
                                              'nullable': False}}},
            'loans': {'kind': 'array',
                      'collection': 'customers',
                      'host': 'customers',
                      'path': ['loans'],
                      'dropped': ['customer_id'],
                      'host_columns': ['id'],
                      'id_column': None,
                      'fields': {'id': 'id',
                                 'principal': 'principal',
                                 'rate': 'rate',
                                 'term_months': 'term_months'},
                      'scalar_column': None,
                      'pk': ['id'],
                      'identity': ['id'],
                      'columns': {'id': {'base': 'INTEGER', 'is_array': False, 'nullable': False},
                                  'customer_id': {'base': 'INTEGER',
                                                  'is_array': False,
                                                  'nullable': False},
                                  'principal': {'base': 'DECIMAL',
                                                'is_array': False,
                                                'nullable': False},
                                  'rate': {'base': 'DOUBLE', 'is_array': False, 'nullable': False},
                                  'term_months': {'base': 'INTEGER',
                                                  'is_array': False,
                                                  'nullable': False}}},
            'beneficiaries': {'kind': 'ref_docs',
                              'collection': 'accounts',
                              'host': 'accounts',
                              'path': ['beneficiaries'],
                              'dropped': ['account_id'],
                              'host_columns': ['id'],
                              'id_column': None,
                              'fields': {'customer_id': 'customer_id', 'nickname': 'nickname'},
                              'scalar_column': None,
                              'pk': ['customer_id', 'account_id'],
                              'identity': [],
                              'columns': {'customer_id': {'base': 'INTEGER',
                                                          'is_array': False,
                                                          'nullable': False},
                                          'account_id': {'base': 'INTEGER',
                                                         'is_array': False,
                                                         'nullable': False},
                                          'nickname': {'base': 'TEXT',
                                                       'is_array': False,
                                                       'nullable': True}}}},
 'relationships': [{'id': 'fk:customers.home_branch_id->branches.id',
                    'child': 'customers',
                    'parent': 'branches',
                    'columns': ['home_branch_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'SET NULL',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:kyc_profiles.customer_id->customers.id',
                    'child': 'kyc_profiles',
                    'parent': 'customers',
                    'columns': ['customer_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:accounts.customer_id->customers.id',
                    'child': 'accounts',
                    'parent': 'customers',
                    'columns': ['customer_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'NO ACTION',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:accounts.branch_id->branches.id',
                    'child': 'accounts',
                    'parent': 'branches',
                    'columns': ['branch_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'NO ACTION',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:transactions.account_id->accounts.id',
                    'child': 'transactions',
                    'parent': 'accounts',
                    'columns': ['account_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:cards.account_id->accounts.id',
                    'child': 'cards',
                    'parent': 'accounts',
                    'columns': ['account_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:loans.customer_id->customers.id',
                    'child': 'loans',
                    'parent': 'customers',
                    'columns': ['customer_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'RESTRICT',
                    'on_update': 'NO ACTION',
                    'embedded': True},
                   {'id': 'fk:beneficiaries.customer_id->customers.id',
                    'child': 'beneficiaries',
                    'parent': 'customers',
                    'columns': ['customer_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': False},
                   {'id': 'fk:beneficiaries.account_id->accounts.id',
                    'child': 'beneficiaries',
                    'parent': 'accounts',
                    'columns': ['account_id'],
                    'ref_columns': ['id'],
                    'on_delete': 'CASCADE',
                    'on_update': 'NO ACTION',
                    'embedded': True}],
 'defaults': {'customers': {'created_at': {'kind': 'now', 'value': None}},
              'kyc_profiles': {'verified': {'kind': 'literal', 'value': False}},
              'accounts': {'balance': {'kind': 'literal', 'value': 0},
                           'opened_at': {'kind': 'now', 'value': None}},
              'transactions': {'created_at': {'kind': 'now', 'value': None}}},
 'unique': {'branches': [['name']],
            'customers': [['email'], ['phone']],
            'kyc_profiles': [['national_id']],
            'cards': [['number']]}}


# --- Runtime of the generated ... (runtime elided) ...

# ---- per-table helpers (generated) ------------------------------------------

def insert_accounts(db, values, session=None):
    # Mitigates:
    #   auto_increment:accounts.id (CHANGED): EQ-AUTOINC
    #   default:accounts.balance (CHANGED): EQ-DEFAULT
    #   default:accounts.opened_at (CHANGED): EQ-DEFAULT
    #   fk:accounts.customer_id->customers.id (CHANGED): EQ-REF-INTEGRITY
    #   fk:accounts.branch_id->branches.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO accounts: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'accounts', values, session)


def delete_accounts(client, db, **match):
    # Mitigates:
    #   cascade_delete:transactions.account_id->accounts.id (BROKEN): EQ-CASCADE-DEL
    #   cascade_delete:beneficiaries.account_id->accounts.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM accounts WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'accounts', match, session)
    )


def update_accounts(client, db, match, changes):
    """UPDATE accounts SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'accounts', match, changes, session
        ),
    )


def insert_beneficiaries(db, values, session=None):
    # Mitigates:
    #   pk:beneficiaries.customer_id,account_id (CHANGED): EQ-ENTITY-UNIQ
    #   fk:beneficiaries.customer_id->customers.id (CHANGED): EQ-REF-INTEGRITY
    #   fk:beneficiaries.account_id->accounts.id (CHANGED): EQ-REF-INTEGRITY
    #   cross_unique:beneficiaries.customer_id,account_id (BROKEN): EQ-CROSS-UNIQ
    """INSERT INTO beneficiaries: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'beneficiaries', values, session)


def delete_beneficiaries(client, db, **match):
    """DELETE FROM beneficiaries WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'beneficiaries', match, session)
    )


def insert_branches(db, values, session=None):
    # Mitigates:
    #   auto_increment:branches.id (CHANGED): EQ-AUTOINC
    """INSERT INTO branches: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'branches', values, session)


def delete_branches(client, db, **match):
    # Mitigates:
    #   set_null:customers.home_branch_id->branches.id (BROKEN): EQ-SET-NULL
    #   restrict_delete:accounts.branch_id->branches.id (CHANGED): EQ-RESTRICT
    """DELETE FROM branches WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'branches', match, session)
    )


def update_branches(client, db, match, changes):
    """UPDATE branches SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'branches', match, changes, session
        ),
    )


def insert_cards(db, values, session=None):
    # Mitigates:
    #   auto_increment:cards.id (CHANGED): EQ-AUTOINC
    #   pk:cards.id (CHANGED): EQ-ENTITY-UNIQ
    #   unique:cards.number (CHANGED): EQ-VALUE-UNIQ
    """INSERT INTO cards: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'cards', values, session)


def delete_cards(client, db, **match):
    """DELETE FROM cards WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'cards', match, session)
    )


def insert_customers(db, values, session=None):
    # Mitigates:
    #   auto_increment:customers.id (CHANGED): EQ-AUTOINC
    #   default:customers.created_at (CHANGED): EQ-DEFAULT
    #   unique:customers.phone (CHANGED): EQ-VALUE-UNIQ
    #   fk:customers.home_branch_id->branches.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO customers: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'customers', values, session)


def delete_customers(client, db, **match):
    # Mitigates:
    #   restrict_delete:accounts.customer_id->customers.id (CHANGED): EQ-RESTRICT
    #   restrict_delete:loans.customer_id->customers.id (CHANGED): EQ-RESTRICT
    #   cascade_delete:beneficiaries.customer_id->customers.id (BROKEN): EQ-CASCADE-DEL
    """DELETE FROM customers WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'customers', match, session)
    )


def update_customers(client, db, match, changes):
    """UPDATE customers SET <changes> WHERE <match> honouring ON UPDATE."""
    return run_in_transaction(
        client,
        lambda session: update_row(
            db, PLAN, 'customers', match, changes, session
        ),
    )


def insert_kyc_profiles(db, values, session=None):
    # Mitigates:
    #   default:kyc_profiles.verified (CHANGED): EQ-DEFAULT
    """INSERT INTO kyc_profiles: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'kyc_profiles', values, session)


def delete_kyc_profiles(client, db, **match):
    """DELETE FROM kyc_profiles WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'kyc_profiles', match, session)
    )


def insert_loans(db, values, session=None):
    # Mitigates:
    #   auto_increment:loans.id (CHANGED): EQ-AUTOINC
    #   pk:loans.id (CHANGED): EQ-ENTITY-UNIQ
    """INSERT INTO loans: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'loans', values, session)


def delete_loans(client, db, **match):
    """DELETE FROM loans WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'loans', match, session)
    )


def insert_transactions(db, values, session=None):
    # Mitigates:
    #   auto_increment:transactions.id (CHANGED): EQ-AUTOINC
    #   default:transactions.created_at (CHANGED): EQ-DEFAULT
    #   fk:transactions.account_id->accounts.id (CHANGED): EQ-REF-INTEGRITY
    """INSERT INTO transactions: defaults, identity ids, FK and uniqueness checks."""
    return insert_row(db, PLAN, 'transactions', values, session)


def delete_transactions(client, db, **match):
    """DELETE FROM transactions WHERE <match> honouring ON DELETE (one transaction)."""
    return run_in_transaction(
        client, lambda session: delete_row(db, PLAN, 'transactions', match, session)
    )
