# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Indexes: unique constraints and foreign-key equivalents."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def create_indexes(db):
    # unique:branches.name: unique
    db['branches'].create_index([['name', 1]], **{'name': 'uq_branches_name', 'unique': True})
    # unique:customers.email: unique
    db['customers'].create_index([['email', 1]], **{'name': 'uq_customers_email', 'unique': True})
    # unique:customers.phone: unique; partial so that NULLs (absent fields) do not collide
    db['customers'].create_index([['phone', 1]], **{
        'name': 'uq_customers_phone',
        'unique': True,
        'partialFilterExpression': {'phone': {'$exists': True}},
    })
    # unique:kyc_profiles.national_id: unique; partial because parents without embedded rows have no such field
    db['customers'].create_index([['kyc_profiles.national_id', 1]], **{
        'name': 'uq_customers_kyc_profiles_national_id',
        'unique': True,
        'partialFilterExpression': {'kyc_profiles.national_id': {'$exists': True}},
    })
    # unique:cards.number: unique; partial because parents without embedded rows have no such field
    db['accounts'].create_index([['cards.number', 1]], **{
        'name': 'uq_accounts_cards_number',
        'unique': True,
        'partialFilterExpression': {'cards.number': {'$exists': True}},
    })
    # fk:customers.home_branch_id->branches.id: supports lookups along the foreign key
    db['customers'].create_index([['home_branch_id', 1]], **{'name': 'idx_customers_home_branch_id'})
    # fk:accounts.customer_id->customers.id: supports lookups along the foreign key
    db['accounts'].create_index([['customer_id', 1]], **{'name': 'idx_accounts_customer_id'})
    # fk:accounts.branch_id->branches.id: supports lookups along the foreign key
    db['accounts'].create_index([['branch_id', 1]], **{'name': 'idx_accounts_branch_id'})
    # fk:transactions.account_id->accounts.id: supports lookups along the foreign key
    db['transactions'].create_index([['account_id', 1]], **{'name': 'idx_transactions_account_id'})
    # fk:beneficiaries.customer_id->customers.id: supports lookups along the foreign key
    db['accounts'].create_index([['beneficiaries.customer_id', 1]], **{'name': 'idx_accounts_beneficiaries_customer_id'})
