# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Translated queries (each function takes a pymongo Database)."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def q1(db):
    """SELECT a.id, COUNT(*) AS n, SUM(t.amount) AS total FROM accounts a JOIN transactions t ON t.account_id = a.id GROUP BY a.id"""
    # q1: SELECT a.id, COUNT(*) AS n, SUM(t.amount) AS total FROM accounts a JOIN transactions t ON t.account_id = a.id GROUP BY a.id
    # columns: id, n, total
    result = list(db['accounts'].aggregate([
            {'$replaceRoot': {'newRoot': {'a': '$$ROOT'}}},
            {
                '$lookup': {'from': 'transactions', 'localField': 'a._id', 'foreignField': 'account_id', 'as': 't'},
            },
            {'$unwind': {'path': '$t', 'preserveNullAndEmptyArrays': False}},
            {
                '$group': {
                    '_id': {'g0': '$a._id'},
                    '__a0': {'$sum': 1},
                    '__a1': {'$sum': '$t.amount'},
                    '__a1_n': {'$sum': {'$cond': [{'$gt': ['$t.amount', None]}, 1, 0]}},
                },
            },
            {
                '$addFields': {
                    'id': {'$ifNull': ['$_id.g0', None]},
                    'n': {'$ifNull': ['$__a0', None]},
                    'total': {'$ifNull': [{'$cond': [{'$eq': ['$__a1_n', 0]}, None, '$__a1']}, None]},
                },
            },
            {'$project': {'_id': 0, 'id': 1, 'n': 1, 'total': 1}},
        ]))
    return result

def q2(db):
    """SELECT c.full_name, k.national_id FROM customers c JOIN kyc_profiles k ON k.customer_id = c.id"""
    # q2: SELECT c.full_name, k.national_id FROM customers c JOIN kyc_profiles k ON k.customer_id = c.id
    # columns: full_name, national_id
    result = list(db['customers'].aggregate([
            {'$replaceRoot': {'newRoot': {'c': '$$ROOT'}}},
            {'$match': {'c.kyc_profiles': {'$exists': True}}},
            {
                '$project': {
                    '_id': 0,
                    'full_name': {'$ifNull': ['$c.full_name', None]},
                    'national_id': {'$ifNull': ['$c.kyc_profiles.national_id', None]},
                },
            },
        ]))
    return result

def q3(db):
    """SELECT c.full_name, a.balance FROM customers c LEFT JOIN accounts a ON a.customer_id = c.id"""
    # q3: SELECT c.full_name, a.balance FROM customers c LEFT JOIN accounts a ON a.customer_id = c.id
    # columns: full_name, balance
    result = list(db['customers'].aggregate([
            {'$replaceRoot': {'newRoot': {'c': '$$ROOT'}}},
            {
                '$lookup': {'from': 'accounts', 'localField': 'c._id', 'foreignField': 'customer_id', 'as': 'a'},
            },
            {'$unwind': {'path': '$a', 'preserveNullAndEmptyArrays': True}},
            {
                '$project': {
                    '_id': 0,
                    'full_name': {'$ifNull': ['$c.full_name', None]},
                    'balance': {'$ifNull': ['$a.balance', None]},
                },
            },
        ]))
    return result

def q4(db):
    """SELECT SUM(balance) FROM accounts"""
    # q4: SELECT SUM(balance) FROM accounts
    # columns: sum
    result = list(db['accounts'].aggregate([
            {'$replaceRoot': {'newRoot': {'accounts': '$$ROOT'}}},
            {
                '$group': {
                    '_id': None,
                    '__a0': {'$sum': '$accounts.balance'},
                    '__a0_n': {'$sum': {'$cond': [{'$gt': ['$accounts.balance', None]}, 1, 0]}},
                },
            },
            {
                '$addFields': {'sum': {'$ifNull': [{'$cond': [{'$eq': ['$__a0_n', 0]}, None, '$__a0']}, None]}},
            },
            {'$project': {'_id': 0, 'sum': 1}},
        ]))
    return result

def txn_t1(client, db):
    """Transaction t1: all-or-nothing across collections."""
    def body(session):
        # q5: UPDATE accounts SET balance = balance - 100 WHERE id = 1
        db['accounts'].update_many({'_id': 1}, [{'$set': {'balance': {'$subtract': ['$balance', 100]}}}], session=session)
        # q6: UPDATE accounts SET balance = balance + 100 WHERE id = 2
        db['accounts'].update_many({'_id': 2}, [{'$set': {'balance': {'$add': ['$balance', 100]}}}], session=session)
        # q7: INSERT INTO transactions (account_id, kind, amount) VALUES (1, 'transfer', 100)
        # note: transactions.id is auto-generated: allocated by the insert helper (counter or ObjectId), not by this statement
        db['transactions'].insert_one({
                'account_id': 1,
                'kind': 'transfer',
                'amount': Decimal128('100'),
                'created_at': datetime.now(timezone.utc),
            }, session=session)
    with client.start_session() as session:
        session.with_transaction(body)
