# Generated by SchemaShift 0.1.0. Do not edit manually.
# Run: snapshot    Generated at: 2026-01-01T00:00:00Z

"""Collections with $jsonSchema validators."""

from datetime import datetime, timezone
import uuid

from bson import Decimal128
from bson.regex import Regex


def ensure_collection(db, name, options):
    """Create the collection, or update its validator when it already exists."""
    if name not in db.list_collection_names():
        db.create_collection(name, **{
            "validator": options["validator"],
            "validationLevel": options["validationLevel"],
            "validationAction": options["validationAction"],
        })
    else:
        db.command("collMod", name, **options)


def create_collections(db):
    # accounts: SQL table accounts; _id = accounts.id
    ensure_collection(db, 'accounts', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['customer_id', 'branch_id', 'kind', 'balance', 'opened_at'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'customer_id': {'bsonType': 'int'},
                    'branch_id': {'bsonType': 'int'},
                    'kind': {'bsonType': 'string', 'enum': ['checking', 'savings', 'business']},
                    'balance': {'bsonType': 'decimal', 'minimum': 0},
                    'opened_at': {'bsonType': 'date'},
                    'beneficiaries': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['customer_id'],
                            'properties': {'customer_id': {'bsonType': 'int'}, 'nickname': {'bsonType': 'string'}},
                            'additionalProperties': False,
                        },
                    },
                    'cards': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['id', 'number', 'expires'],
                            'properties': {
                                'id': {'bsonType': 'int'},
                                'number': {'bsonType': 'string', 'maxLength': 16},
                                'expires': {'bsonType': 'date'},
                            },
                            'additionalProperties': False,
                        },
                    },
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # branches: SQL table branches; _id = branches.id
    ensure_collection(db, 'branches', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['name', 'city'],
                'properties': {'_id': {'bsonType': 'int'}, 'name': {'bsonType': 'string'}, 'city': {'bsonType': 'string'}},
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # customers: SQL table customers; _id = customers.id
    ensure_collection(db, 'customers', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['full_name', 'email', 'created_at'],
                'properties': {
                    '_id': {'bsonType': 'int'},
                    'full_name': {'bsonType': 'string'},
                    'email': {'bsonType': 'string'},
                    'phone': {'bsonType': 'string'},
                    'home_branch_id': {'bsonType': 'int'},
                    'created_at': {'bsonType': 'date'},
                    'kyc_profiles': {
                        'bsonType': 'object',
                        'required': ['national_id', 'verified'],
                        'properties': {
                            'national_id': {'bsonType': 'string'},
                            'verified': {'bsonType': 'bool'},
                            'verified_at': {'bsonType': 'date'},
                        },
                        'additionalProperties': False,
                    },
                    'loans': {
                        'bsonType': 'array',
                        'items': {
                            'bsonType': 'object',
                            'required': ['id', 'principal', 'rate', 'term_months'],
                            'properties': {
                                'id': {'bsonType': 'int'},
                                'principal': {'bsonType': 'decimal'},
                                'rate': {'bsonType': 'number', 'minimum': 0.0, 'maximum': 1.0},
                                'term_months': {'bsonType': 'int'},
                            },
                            'additionalProperties': False,
                        },
                    },
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
    # transactions: SQL table transactions; _id = transactions.id
    ensure_collection(db, 'transactions', {
        'validator': {
            '$jsonSchema': {
                'bsonType': 'object',
                'required': ['account_id', 'kind', 'amount', 'created_at'],
                'properties': {
                    '_id': {'bsonType': ['int', 'long']},
                    'account_id': {'bsonType': 'int'},
                    'kind': {'bsonType': 'string', 'enum': ['deposit', 'withdrawal', 'transfer']},
                    'amount': {'bsonType': 'decimal', 'minimum': 0, 'exclusiveMinimum': True},
                    'created_at': {'bsonType': 'date'},
                    'memo': {'bsonType': 'string'},
                },
                'additionalProperties': False,
            },
        },
        'validationLevel': 'strict',
        'validationAction': 'error',
    })
